package main

//go:generate go run github.com/valyala/quicktemplate/qtc

import (
	"bufio"
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"io/ioutil"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/turutcrane/cefingo/tools/gen-cefingo/parser"
)

var (
	goFormat     bool = true
	fileComments map[int][]string
	capiDir      = flag.String("capidir", "capi", "outpu directory")
)

func main() {
	flag.Parse()
	tus := parser.Parse()
	for i, tu := range tus {
		parser.ExternalDeclaration(i, tu.ExternalDeclaration)
	}
	goTypeFile := newFileGo("cefingo_types_gen.go", false)
	defer outFileGo(goTypeFile)

	goTypeWinFile := newFileGo("cefingo_types_win_gen.go", false)
	defer outFileGo(goTypeWinFile)

	goExportFile := newFileGo("cefingo_exports_gen.go", false)
	defer outFileGo(goExportFile)

	cFile, hFile := newFileCH()
	defer outFileCH(cFile, hFile)

	var goFile *Generator
	fn := []string{}
	for fname, _ := range parser.TargetFileList {
		fn = append(fn, fname)
	}
	sort.Strings(fn)

	goGenFile := newFileGo("cefingo_gen.go", true)
	for _, fname := range fn {
		log.Printf("T35: Process %s\n", fname)
		if strings.HasSuffix(fname, "_capi.h") {
			goFile = goGenFile // newFileGo(makeGoFileName(fname), parser.HasHandlerClass(fname))
		} else if fname == "cef_types_win.h" {
			goFile = goTypeWinFile
		} else {
			goFile = goTypeFile
		}
		log.Printf("T13: %s\n", fname)
		a := parser.FileDefs[fname]
		first := true
		for _, d := range a {
			token := d.Common().Token()
			if first {
				getComments(token.AbsFilename())
				goFile.Printf("\n// %s, %s, \n", fname, token.FilePos())
				first = false
			}
			d.SetComment(fileComments)
			switch d.Common().Dk {
			case parser.DkSimple:
				s := d.(*parser.SimpleDecl)
				outSimple(goFile, s)
			case parser.DkStruct:
				if s, ok := d.(*parser.StructDecl); ok {
					outStruct(goFile, s)
				} else if s, ok := d.(*parser.SimpleDecl); ok {
					outSimple(goFile, s)
				} else {
					log.Panicf("T84: Can not handle: %v\n", d)
				}
			case parser.DkEnum:
				e := d.(*parser.EnumDecl)
				outEnum(goFile, e)
			case parser.DkCefClass:
				s := d.(*parser.CefClassDecl)
				if parser.IsHandlerClass(s.Token()) {
					outHandlerClass(goFile, goExportFile, cFile, hFile, s)
				} else {
					outCefObjectClass(goFile, cFile, hFile, s)
				}
			case parser.DkFunc:
				f := d.(*parser.FuncDecl)
				outGoFunction(goFile, f)
			default:
				log.Printf("T31: %s: %s\n", d.Common().Dk, token.Name())
			}
		}
		if strings.HasSuffix(fname, "_capi.h") {
			log.Printf("T63: %s\n", fname)
			outFileGo(goFile)
		}
	}

	log.Printf("T10: End: %d Translation Units", len(tus))
}

func newFileGo(fname string, hasCallbackClass bool) (gf *Generator) {
	gf = &Generator{}
	gf.fname = fname

	var imports []string
	var defIfMutex bool
	var winOnly bool
	if fname == "cefingo_types_gen.go" {
		imports = []string{"sync", "time", "unsafe"}
		defIfMutex = true
	} else if fname == "cefingo_exports.go" {
		imports = []string{"unsafe", "runtime"}
	} else if fname == "cefingo_types_win_gen.go" {
		winOnly = true
	} else {
		imports = []string{"unsafe", "runtime"}
	}

	WriteGoHead(gf, imports, defIfMutex, winOnly)
	return gf
}

func makeGoFileName(capiH string) (gfile string) {
	if strings.HasSuffix(capiH, "_capi.h") {
		name := strings.Replace(capiH, "cef_", "", 1)
		name = strings.Replace(name, "_capi.h", "", 1)
		gfile = name + "_gen.go"
	} else {
		log.Panicf("T117: Wrong file: %s\n", capiH)
	}

	return gfile
}

func outFileGo(gf *Generator) {
	// Format the output.
	var src []byte
	if goFormat {
		src = gf.format()
	} else {
		gf.Printf("// Not Formatted.!")
		src = gf.buf.Bytes()
	}

	// Write to file.
	outputName := filepath.Join(*capiDir, gf.fname)

	err := ioutil.WriteFile(outputName, src, 0644)
	if err != nil {
		log.Panicf("writing output: %s", err)
	}
}

func newFileCH() (cFile, hFile *Generator) {
	cFile = &Generator{}
	cFile.Printf(`// Code generated by "genCefingo.go" DO NOT EDIT.
#include "cefingo.h"
#include "_cgo_export.h"
`)

	hFile = &Generator{}
	hFile.Printf(`// Code generated by "genCefingo.go" DO NOT EDIT.
#ifndef CEFINGO_GEN_H_
#define CEFINGO_GEN_H_
`)
	return cFile, hFile
}

func outFileCH(cFile, hFile *Generator) {

	// Write to C file.
	outputCName := filepath.Join(*capiDir, "cefingo_gen.c")
	err := ioutil.WriteFile(outputCName, cFile.buf.Bytes(), 0644)
	if err != nil {
		log.Panicf("writing output: %s", err)
	}

	// Write to H file.
	hFile.Printf("#endif //CEFINGO_GEN_H_")
	outputHName := filepath.Join(*capiDir, "cefingo_gen.h")
	err = ioutil.WriteFile(outputHName, hFile.buf.Bytes(), 0644)
	if err != nil {
		log.Panicf("writing output: %s", err)
	}
}

func outComment(gf *Generator, line int) {
	if comments, ok := fileComments[line]; ok {
		gf.Printf("\n")
		for _, c := range comments {
			gf.Printf("%s\n", c)
		}
	}
}

func outSimple(gf *Generator, d *parser.SimpleDecl) {
	line := d.LineOfTypedef()
	outComment(gf, line)
	// fmt.Fprintf(fileGoTypes, "// Pos: %d\n", d.Line())
	gf.Printf("type %s C.%s\n", d.GoName(), d.CefName())
}

func outStruct(gf *Generator, d *parser.StructDecl) {
	line := d.LineOfTypedef()
	outComment(gf, line)
	// fmt.Fprintf(fileGoTypes, "// Pos: %d\n", d.Line())
	gf.Printf("type %s C.%s\n", d.GoName(), d.CefName())
	WriteNewStruct(gf, d)
	for i, m := range d.Members {
		if !(i == 0 && m.Type().Ty == parser.TySizeT && m.Name() == "size") {
			WriteMemberAccessor(gf, d, m)
		}
	}
}

func outEnum(gf *Generator, d *parser.EnumDecl) {
	outComment(gf, d.LineOfTypedef())
	gf.Printf("type %s C.%s\n", d.GoName(), d.CefName())
	gf.Printf("const (\n")
	for _, e := range d.Enums {
		outComment(gf, e.Line())
		gf.Printf("\t%s %s = C.%s\n", e.TitleCase(), d.GoName(), e.Name())
	}
	gf.Printf(")\n")
}

func getComments(fname string) {
	fileComments = map[int][]string{}
	f, err := os.Open(fname)
	if err != nil {
		log.Panicf("T186: %s, %v", fname, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	line := 0
	comment := false
	cRegex := regexp.MustCompile("^[[:blank:]]*//")
	var block []string
	for scanner.Scan() {
		line++
		b := scanner.Bytes()
		if cRegex.Match(b) {
			if comment {
				block = append(block, strings.TrimLeft(scanner.Text(), " "))
			} else {
				comment = true
				block = []string{strings.TrimLeft(scanner.Text(), " ")}
			}
		} else {
			if comment {
				fileComments[line] = block
				// fmt.Printf("T111: %d: %s\n", line, scanner.Text())
			}
			comment = false
		}
	}
}

func outHandlerClass(gf, expf, cf, hf *Generator, d *parser.CefClassDecl) {
	log.Printf("T226: Callback class: %s\n", d.Token())
	outComment(gf, d.LineOfTypedef())
	WriteGoType(gf, d, gf.Lines())
	genGoInterface(gf, d)
	genGoAlloc(gf, d)
	genBindFunc(gf, d)
	genGoGetFunc(gf, expf, d)
	genGoCallbackFunc(expf, d)
	genChConstructFunc(cf, hf, d)
}

func genGoInterface(gf *Generator, st *parser.CefClassDecl) {
	line := gf.Lines()
	for _, m := range st.Methods {
		if !m.IsGetFunc() {
			WriteGoIface(gf, line, m)
		}
	}
	WriteIfaceStruct(gf, line, st)
}

func genGoAlloc(gf *Generator, st *parser.CefClassDecl) {
	line := gf.Lines()
	WriteGoAllocFunc(gf, line, st)
}

func genBindFunc(gf *Generator, st *parser.CefClassDecl) {
	line := gf.Lines()
	WriteGoBindFunc(gf, line, st)
}

func genGoGetFunc(gf, expf *Generator, st *parser.CefClassDecl) {
	goName := st.GoName()
	baseName := st.BaseName()
	cName := st.CefName()
	for c := st; c != nil; c = c.GetBase() {
		for _, m := range c.Methods {
			if m.IsGetFunc() {
				line := expf.Lines()
				WriteGoGetFunc(expf, line, m, goName, baseName, cName)
				line = gf.Lines()
				WriteAssocGetFunc(gf, line, m, goName, baseName, cName)
			}
		}
	}
}

func genGoCallbackFunc(gf *Generator, st *parser.CefClassDecl) {
	for c := st; c != nil; c = c.GetBase() {
		for _, m := range c.Methods {
			if !m.IsGetFunc() {
				line := gf.Lines()
				WriteGoCallback(gf, line, m, st)
			}
		}
	}
}

func ConvToGoTypeExp(t parser.Type, val string) (exp string) {
	switch t.Ty {
	case parser.TyInt, parser.TyInt32, parser.TyInt64, parser.TyUint32, parser.TyUint64,
		parser.TyFloat, parser.TyDouble,
		parser.TyStructSimple, parser.TySimple, parser.TySizeT, parser.TyHWND, parser.TyHCURSOR:
		exp = "(" + t.GoType() + ")(" + val + ")"
	case parser.TyStructRefCounted:
		if t.Pointer == 1 {
			exp = "new" + t.Deref().GoType() + "(" + val + ")"
		} else {
			log.Panicf("T448: %s: %v, %t, %v\n", val, t.Ty, t.IsRefCountedClass(), t.GoType())
		}
	case parser.TyStructScoped:
		if t.Pointer == 1 {
			exp = "new" + t.Deref().GoType() + "(" + val + ")"
		} else {
			log.Panicf("T454: %s: %v\n", val, t)
		}
	case parser.TyStringT:
		if t.Pointer == 1 {
			exp = "string_from_cef_string(" + val + ")"
		} else {
			log.Panicf("T460: %s: %v\n", val, t)
		}
	case parser.TyEnum:
		exp = t.GoType() + "(" + val + ")"
	case parser.TyVoid:
		switch t.Pointer {
		case 1:
			exp = "unsafe.Pointer(" + val + ")"
		default:
			log.Panicf("T474: %s: %v\n", val, t)
		}
	case parser.TyMSG:
		if t.Pointer == 1 {
			exp = t.Deref().GoType() + "(" + val + ")"
		} else {
			log.Panicf("E326: %v\n", t)
		}
	default:
		log.Panicf("T456: %s: %v\n", val, t)
	}
	return exp
}

func genChConstructFunc(cf, hf *Generator, st *parser.CefClassDecl) {
	line := cf.Lines()
	WriteCConstruct(cf, line, st)

	line = hf.Lines()
	WriteHCallback(hf, line, st)
}

func outCefObjectClass(gf, cf, hf *Generator, d *parser.CefClassDecl) {
	log.Printf("T541: Cef object: %s\n", d.Token())
	outComment(gf, d.LineOfTypedef())
	WriteGoType(gf, d, gf.Lines())
	outCefObjectMethod(gf, cf, hf, d)
}

func outGoFunction(gf *Generator, f *parser.FuncDecl) {
	log.Printf("T350: Cef Functin : %s\n", f.Token())
	outComment(gf, f.LineOfTypedef())
	WriteGoFunction(gf, gf.Lines(), f)
}

func outCefObjectMethod(gf, cf, hf *Generator, d *parser.CefClassDecl) {
	for _, m := range d.Methods {
		WriteCefObjectMethod(gf, gf.Lines(), m)
		WriteCefObjectMethodC(cf, m)
		WriteCefObjectMethodH(hf, m)
	}
}

// Generator holds the state of the analysis. Primarily used to buffer
// the output for format.Source.
type Generator struct {
	fname string
	buf   bytes.Buffer // Accumulated output.
}

func (g *Generator) Printf(format string, args ...interface{}) {
	fmt.Fprintf(&g.buf, format, args...)
}

func (g *Generator) Write(p []byte) (n int, err error) {
	return g.buf.Write(p)
}

func (g *Generator) Lines() (line int) {
	return bytes.Count(g.buf.Bytes(), []byte("\n"))
}

// format returns the gofmt-ed contents of the Generator's buffer.
func (g *Generator) format() []byte {
	src, err := format.Source(g.buf.Bytes())
	if err != nil {
		// Should never happen, but can arise when developing this code.
		// The user can compile the output to see the error.
		log.Printf("warning: internal error: invalid Go generated: %s", err)
		log.Printf("warning: compile the package to analyze the error")
		return g.buf.Bytes()
	}
	return src
}
