// Code generated by qtc from "template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template.qtpl:1
package main

//line template.qtpl:2
import (
	"log"
	"strings"

	"github.com/turutcrane/cefingo/tools/gen-cefingo/parser"
)

// Generate parameter name for Go func.

//line template.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template.qtpl:10
func streamgoParamName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:11
	switch p.Name() {
//line template.qtpl:12
	case "type", "string", "map", "time":
//line template.qtpl:13
		qw422016.E().S("c" + p.Name())
//line template.qtpl:14
	default:
//line template.qtpl:15
		qw422016.E().S(p.Name())
//line template.qtpl:16
	}
//line template.qtpl:17
}

//line template.qtpl:17
func writegoParamName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:17
	streamgoParamName(qw422016, p)
//line template.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:17
}

//line template.qtpl:17
func goParamName(p parser.Param) string {
//line template.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:17
	writegoParamName(qb422016, p)
//line template.qtpl:17
	qs422016 := string(qb422016.B)
//line template.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:17
	return qs422016
//line template.qtpl:17
}

// Generate parameter name for Go func.

//line template.qtpl:20
func streamgoParamNameOut(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:21
	streamgoParamName(qw422016, p)
//line template.qtpl:22
	if p.IsInOutParam() {
//line template.qtpl:22
		qw422016.N().S(`Out`)
//line template.qtpl:22
	}
//line template.qtpl:23
}

//line template.qtpl:23
func writegoParamNameOut(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:23
	streamgoParamNameOut(qw422016, p)
//line template.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:23
}

//line template.qtpl:23
func goParamNameOut(p parser.Param) string {
//line template.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:23
	writegoParamNameOut(qb422016, p)
//line template.qtpl:23
	qs422016 := string(qb422016.B)
//line template.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:23
	return qs422016
//line template.qtpl:23
}

//line template.qtpl:25
func streamgoTempName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:25
	qw422016.N().S(`goTmp`)
//line template.qtpl:26
	qw422016.E().S(p.Name())
//line template.qtpl:27
}

//line template.qtpl:27
func writegoTempName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:27
	streamgoTempName(qw422016, p)
//line template.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:27
}

//line template.qtpl:27
func goTempName(p parser.Param) string {
//line template.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:27
	writegoTempName(qb422016, p)
//line template.qtpl:27
	qs422016 := string(qb422016.B)
//line template.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:27
	return qs422016
//line template.qtpl:27
}

//line template.qtpl:29
func streamgoTempNameOut(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:30
	qw422016.E().S(goTempName(p) + "Out")
//line template.qtpl:31
}

//line template.qtpl:31
func writegoTempNameOut(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:31
	streamgoTempNameOut(qw422016, p)
//line template.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:31
}

//line template.qtpl:31
func goTempNameOut(p parser.Param) string {
//line template.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:31
	writegoTempNameOut(qb422016, p)
//line template.qtpl:31
	qs422016 := string(qb422016.B)
//line template.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:31
	return qs422016
//line template.qtpl:31
}

// Statemens to convert from C.param to Go type.

//line template.qtpl:34
func streamconvToGoTypeStmts(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:35
	if p.IsInOutParam() {
//line template.qtpl:36
		if p.Type().Ty == parser.TyStringT {
//line template.qtpl:36
			qw422016.N().S(`		`)
//line template.qtpl:37
			streamgoTempName(qw422016, p)
//line template.qtpl:37
			qw422016.N().S(` := string_from_cef_string(`)
//line template.qtpl:37
			qw422016.E().S(goParamName(p))
//line template.qtpl:37
			qw422016.N().S(`)
`)
//line template.qtpl:38
		} else if p.Type().Pointer == 2 && p.Type().Deref().IsRefCountedClass() {
//line template.qtpl:38
			qw422016.N().S(`		`)
//line template.qtpl:39
			streamgoTempName(qw422016, p)
//line template.qtpl:39
			qw422016.N().S(` := `)
//line template.qtpl:39
			qw422016.E().S(ConvToGoTypeExp(p.Type().Deref(), "*"+goParamName(p)))
//line template.qtpl:39
			*line += 1

//line template.qtpl:39
			qw422016.N().S(`
		cefp := `)
//line template.qtpl:40
			qw422016.E().S(goTempName(p))
//line template.qtpl:40
			qw422016.N().S(`.p_`)
//line template.qtpl:40
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:40
			qw422016.N().S(`
`)
//line template.qtpl:41
		} else if p.Type().Ty == parser.TyStructSimple || p.Type().Ty == parser.TyInt {
//line template.qtpl:41
			qw422016.N().S(`		`)
//line template.qtpl:42
			streamgoTempName(qw422016, p)
//line template.qtpl:42
			qw422016.N().S(` := `)
//line template.qtpl:42
			qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:42
			qw422016.N().S(`(*`)
//line template.qtpl:42
			qw422016.E().S(p.Name())
//line template.qtpl:42
			qw422016.N().S(`)
`)
//line template.qtpl:43
		} else {
//line template.qtpl:44
			log.Panicf("E43: %s::%s::%s", p.CalleeName(), p.Name(), p.Type())

//line template.qtpl:45
		}
//line template.qtpl:46
	} else if !p.IsOutParam() {
//line template.qtpl:47
		if bs, maxLenArg := p.IsByteSliceParam(); bs {
//line template.qtpl:47
			qw422016.N().S(`		`)
//line template.qtpl:48
			streamgoTempName(qw422016, p)
//line template.qtpl:48
			qw422016.N().S(` := (*[1 << 30]byte)(`)
//line template.qtpl:48
			qw422016.E().S(p.Name())
//line template.qtpl:48
			qw422016.N().S(`)[:`)
//line template.qtpl:48
			qw422016.E().S(maxLenArg)
//line template.qtpl:48
			qw422016.N().S(`:`)
//line template.qtpl:48
			qw422016.E().S(maxLenArg)
//line template.qtpl:48
			qw422016.N().S(`]`)
//line template.qtpl:48
			*line += 1

//line template.qtpl:48
			qw422016.N().S(`
`)
//line template.qtpl:49
		} else if s, maxLenArg := p.IsSliceParam(); s {
//line template.qtpl:49
			qw422016.N().S(`		slice := (*[1 << 30](`)
//line template.qtpl:50
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:50
			qw422016.N().S(`))(unsafe.Pointer(`)
//line template.qtpl:50
			qw422016.E().S(p.Name())
//line template.qtpl:50
			qw422016.N().S(`))[:`)
//line template.qtpl:50
			qw422016.E().S(maxLenArg)
//line template.qtpl:50
			qw422016.N().S(`:`)
//line template.qtpl:50
			qw422016.E().S(maxLenArg)
//line template.qtpl:50
			qw422016.N().S(`]
		`)
//line template.qtpl:51
			streamgoTempName(qw422016, p)
//line template.qtpl:51
			qw422016.N().S(` := make(`)
//line template.qtpl:51
			qw422016.E().S(p.GoType())
//line template.qtpl:51
			qw422016.N().S(`, `)
//line template.qtpl:51
			qw422016.E().S(maxLenArg)
//line template.qtpl:51
			qw422016.N().S(`)
		for i, v := range slice {
			`)
//line template.qtpl:53
			streamgoTempName(qw422016, p)
//line template.qtpl:53
			qw422016.N().S(`[i] = new`)
//line template.qtpl:53
			qw422016.E().S(p.Type().Deref().Deref().GoType())
//line template.qtpl:53
			qw422016.N().S(`(v)
		}
`)
//line template.qtpl:55
		} else {
//line template.qtpl:56
			if !p.IsSliceLengthParam() {
//line template.qtpl:56
				qw422016.N().S(`		`)
//line template.qtpl:57
				streamgoTempName(qw422016, p)
//line template.qtpl:57
				qw422016.N().S(` := `)
//line template.qtpl:57
				qw422016.E().S(ConvToGoTypeExp(p.Type(), goParamName(p)))
//line template.qtpl:57
				*line += 1

//line template.qtpl:57
				qw422016.N().S(`
`)
//line template.qtpl:58
			}
//line template.qtpl:59
		}
//line template.qtpl:60
	}
//line template.qtpl:61
}

//line template.qtpl:61
func writeconvToGoTypeStmts(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:61
	streamconvToGoTypeStmts(qw422016, p, line)
//line template.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:61
}

//line template.qtpl:61
func convToGoTypeStmts(p parser.Param, line *int) string {
//line template.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:61
	writeconvToGoTypeStmts(qb422016, p, line)
//line template.qtpl:61
	qs422016 := string(qb422016.B)
//line template.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:61
	return qs422016
//line template.qtpl:61
}

// Set returned Go value to C.param and cleanup

//line template.qtpl:64
func streamafterProcess(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:65
	if p.IsOutParam() {
//line template.qtpl:66
		if p.Type().Ty == parser.TyStringT {
//line template.qtpl:66
			qw422016.N().S(`		set_cef_string(`)
//line template.qtpl:67
			streamgoParamName(qw422016, p)
//line template.qtpl:67
			qw422016.N().S(`, `)
//line template.qtpl:67
			streamgoTempNameOut(qw422016, p)
//line template.qtpl:67
			qw422016.N().S(`)`)
//line template.qtpl:67
			*line += 1

//line template.qtpl:67
			qw422016.N().S(`
`)
//line template.qtpl:68
		} else if p.Type().Deref().IsRefCountedClass() {
//line template.qtpl:68
			qw422016.N().S(`		if `)
//line template.qtpl:69
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:69
			qw422016.N().S(` != nil {
			*`)
//line template.qtpl:70
			qw422016.E().S(goParamName(p))
//line template.qtpl:70
			qw422016.N().S(` = `)
//line template.qtpl:70
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:70
			qw422016.N().S(`.p_`)
//line template.qtpl:70
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:70
			qw422016.N().S(`
			BaseAddRef(*`)
//line template.qtpl:71
			qw422016.E().S(goParamName(p))
//line template.qtpl:71
			qw422016.N().S(`)
		}`)
//line template.qtpl:72
			*line += 4

//line template.qtpl:72
			qw422016.N().S(`
`)
//line template.qtpl:73
		} else {
//line template.qtpl:73
			qw422016.N().S(`		*`)
//line template.qtpl:74
			qw422016.E().S(goParamName(p))
//line template.qtpl:74
			qw422016.N().S(` = (`)
//line template.qtpl:74
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:74
			qw422016.N().S(`)(`)
//line template.qtpl:74
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:74
			qw422016.N().S(`)`)
//line template.qtpl:74
			*line += 1

//line template.qtpl:74
			qw422016.N().S(`
`)
//line template.qtpl:75
		}
//line template.qtpl:76
	} else if p.IsInOutParam() {
//line template.qtpl:77
		if p.Type().Ty == parser.TyStringT {
//line template.qtpl:77
			qw422016.N().S(`		set_cef_string(`)
//line template.qtpl:78
			qw422016.E().S(goParamName(p))
//line template.qtpl:78
			qw422016.N().S(`,`)
//line template.qtpl:78
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:78
			qw422016.N().S(`)`)
//line template.qtpl:78
			*line += 1

//line template.qtpl:78
			qw422016.N().S(`
	`)
//line template.qtpl:79
		} else if p.Type().Ty == parser.TyStructSimple || p.Type().Ty == parser.TyInt {
//line template.qtpl:79
			qw422016.N().S(`		*`)
//line template.qtpl:80
			qw422016.E().S(p.Name())
//line template.qtpl:80
			qw422016.N().S(` = `)
//line template.qtpl:80
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:80
			qw422016.N().S(`(`)
//line template.qtpl:80
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:80
			qw422016.N().S(`)
`)
//line template.qtpl:81
		} else if p.Type().Pointer == 2 {
//line template.qtpl:81
			qw422016.N().S(`		if cefp != `)
//line template.qtpl:82
			streamgoTempNameOut(qw422016, p)
//line template.qtpl:82
			qw422016.N().S(`.p_`)
//line template.qtpl:82
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:82
			qw422016.N().S(` {
			*`)
//line template.qtpl:83
			qw422016.E().S(goParamName(p))
//line template.qtpl:83
			qw422016.N().S(` = `)
//line template.qtpl:83
			streamgoTempNameOut(qw422016, p)
//line template.qtpl:83
			qw422016.N().S(`.p_`)
//line template.qtpl:83
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:83
			qw422016.N().S(`
			BaseAddRef(*`)
//line template.qtpl:84
			qw422016.E().S(goParamName(p))
//line template.qtpl:84
			qw422016.N().S(`)
		}
`)
//line template.qtpl:86
		} else {
//line template.qtpl:87
			log.Panicf("E88: %s::%s::%s", p.CalleeName(), p.Name(), p.Type())

//line template.qtpl:88
		}
//line template.qtpl:89
	} else if p.Name() != "self" {
//line template.qtpl:90
		if p.IsRefCountedClass() {
//line template.qtpl:90
			qw422016.N().S(`		BaseRelease(`)
//line template.qtpl:91
			streamgoTempName(qw422016, p)
//line template.qtpl:91
			qw422016.N().S(`.p_`)
//line template.qtpl:91
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:91
			qw422016.N().S(`)
`)
//line template.qtpl:92
			*line += 1

//line template.qtpl:93
		}
//line template.qtpl:94
	}
//line template.qtpl:95
}

//line template.qtpl:95
func writeafterProcess(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:95
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:95
	streamafterProcess(qw422016, p, line)
//line template.qtpl:95
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:95
}

//line template.qtpl:95
func afterProcess(p parser.Param, line *int) string {
//line template.qtpl:95
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:95
	writeafterProcess(qb422016, p, line)
//line template.qtpl:95
	qs422016 := string(qb422016.B)
//line template.qtpl:95
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:95
	return qs422016
//line template.qtpl:95
}

//line template.qtpl:97
func StreamMethodComments(qw422016 *qt422016.Writer, m *parser.MethodDecl, line *int) {
//line template.qtpl:98
	for _, c := range m.Comment {
//line template.qtpl:99
		qw422016.E().S(c)
//line template.qtpl:99
		*line++

//line template.qtpl:99
		qw422016.N().S(`
`)
//line template.qtpl:100
	}
//line template.qtpl:101
}

//line template.qtpl:101
func WriteMethodComments(qq422016 qtio422016.Writer, m *parser.MethodDecl, line *int) {
//line template.qtpl:101
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:101
	StreamMethodComments(qw422016, m, line)
//line template.qtpl:101
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:101
}

//line template.qtpl:101
func MethodComments(m *parser.MethodDecl, line *int) string {
//line template.qtpl:101
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:101
	WriteMethodComments(qb422016, m, line)
//line template.qtpl:101
	qs422016 := string(qb422016.B)
//line template.qtpl:101
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:101
	return qs422016
//line template.qtpl:101
}

//line template.qtpl:103
func streamgoRecieveValue(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:104
	first := true

//line template.qtpl:105
	if m.HasReturnValue() {
//line template.qtpl:105
		qw422016.N().S(`goRet`)
//line template.qtpl:105
		first = false

//line template.qtpl:105
	}
//line template.qtpl:106
	for _, p := range m.Params() {
//line template.qtpl:107
		if p.IsOutParam() || p.IsInOutParam() {
//line template.qtpl:108
			if !first {
//line template.qtpl:108
				qw422016.N().S(`, `)
//line template.qtpl:108
			}
//line template.qtpl:109
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:109
			first = false

//line template.qtpl:110
		}
//line template.qtpl:111
	}
//line template.qtpl:112
	if m.HasReturnValue() || m.HasOutParam() {
//line template.qtpl:112
		qw422016.N().S(`:= `)
//line template.qtpl:112
	}
//line template.qtpl:113
}

//line template.qtpl:113
func writegoRecieveValue(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:113
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:113
	streamgoRecieveValue(qw422016, m)
//line template.qtpl:113
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:113
}

//line template.qtpl:113
func goRecieveValue(m *parser.MethodDecl) string {
//line template.qtpl:113
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:113
	writegoRecieveValue(qb422016, m)
//line template.qtpl:113
	qs422016 := string(qb422016.B)
//line template.qtpl:113
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:113
	return qs422016
//line template.qtpl:113
}

//line template.qtpl:115
func StreamGoCallback(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl, baseName string) {
//line template.qtpl:115
	qw422016.N().S(`
`)
//line template.qtpl:117
	var retCtype string
	retCtype = m.ReturnType().GoCType()

//line template.qtpl:120
	StreamMethodComments(qw422016, m, &line)
//line template.qtpl:120
	qw422016.N().S(`//export cefingo_`)
//line template.qtpl:121
	qw422016.E().S(baseName)
//line template.qtpl:121
	qw422016.N().S(`_`)
//line template.qtpl:121
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:121
	qw422016.N().S(`
func cefingo_`)
//line template.qtpl:122
	qw422016.E().S(baseName)
//line template.qtpl:122
	qw422016.N().S(`_`)
//line template.qtpl:122
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:122
	qw422016.N().S(`(
`)
//line template.qtpl:123
	for _, p := range m.Params() {
//line template.qtpl:123
		qw422016.N().S(`	`)
//line template.qtpl:124
		qw422016.E().S(goParamName(p))
//line template.qtpl:124
		qw422016.N().S(` `)
//line template.qtpl:124
		qw422016.E().S(p.GoCType())
//line template.qtpl:124
		qw422016.N().S(`,`)
//line template.qtpl:124
		line += 1

//line template.qtpl:124
		qw422016.N().S(`
`)
//line template.qtpl:125
	}
//line template.qtpl:125
	qw422016.N().S(`) `)
//line template.qtpl:126
	if retCtype != "" {
//line template.qtpl:126
		qw422016.N().S(`(cRet `)
//line template.qtpl:126
		qw422016.E().S(retCtype)
//line template.qtpl:126
		qw422016.N().S(`)`)
//line template.qtpl:126
	}
//line template.qtpl:126
	qw422016.N().S(` {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()

	Tracef(unsafe.Pointer(self), "T`)
//line template.qtpl:130
	qw422016.N().D(line + 5)
//line template.qtpl:130
	qw422016.N().S(`:")
	cefingoIfaceAccess.Lock()
	f := `)
//line template.qtpl:132
	qw422016.E().S(baseName)
//line template.qtpl:132
	qw422016.N().S(`_handlers.`)
//line template.qtpl:132
	streammemberName(qw422016, m)
//line template.qtpl:132
	qw422016.N().S(`[self]
	cefingoIfaceAccess.Unlock()

	if f != nil {
`)
//line template.qtpl:136
	for _, p := range m.Params() {
//line template.qtpl:137
		if exp := convToGoTypeStmts(p, &line); exp != "" && !p.IsByteSliceLengthParam() {
//line template.qtpl:138
			qw422016.N().S(exp)
//line template.qtpl:139
		}
//line template.qtpl:140
	}
//line template.qtpl:140
	qw422016.N().S(`
		`)
//line template.qtpl:141
	streamgoRecieveValue(qw422016, m)
//line template.qtpl:141
	qw422016.N().S(`f.`)
//line template.qtpl:141
	qw422016.E().S(m.Funcname.TitleCase())
//line template.qtpl:141
	qw422016.E().S("(")
//line template.qtpl:142
	for _, p := range m.Params() {
//line template.qtpl:143
		if !(p.IsSliceLengthParam() || p.IsByteSliceLengthParam() || p.IsOutParam()) {
//line template.qtpl:143
			streamgoTempName(qw422016, p)
//line template.qtpl:143
			qw422016.N().S(`,`)
//line template.qtpl:143
		}
//line template.qtpl:144
	}
//line template.qtpl:144
	qw422016.N().S(`)
`)
//line template.qtpl:145
	for _, p := range m.Params() {
//line template.qtpl:146
		if exp := afterProcess(p, &line); exp != "" {
//line template.qtpl:147
			qw422016.E().S(exp)
//line template.qtpl:148
		}
//line template.qtpl:149
	}
//line template.qtpl:149
	qw422016.N().S(`
`)
//line template.qtpl:150
	if m.IsBoolValueMethod() {
//line template.qtpl:150
		line += 1

//line template.qtpl:150
		qw422016.N().S(`		if goRet {cRet = 1}
`)
//line template.qtpl:152
	} else if m.ReturnType().IsRefCountedClass() {
//line template.qtpl:152
		line += 1

//line template.qtpl:152
		qw422016.N().S(`		cRet = (`)
//line template.qtpl:153
		qw422016.E().S(retCtype)
//line template.qtpl:153
		qw422016.N().S(`)(goRet.p_`)
//line template.qtpl:153
		qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:153
		qw422016.N().S(`)
		BaseAddRef(cRet)
`)
//line template.qtpl:155
	} else if retCtype != "" {
//line template.qtpl:155
		line += 1

//line template.qtpl:155
		qw422016.N().S(`		cRet = (`)
//line template.qtpl:156
		qw422016.E().S(retCtype)
//line template.qtpl:156
		qw422016.N().S(`)(goRet)
`)
//line template.qtpl:157
	}
//line template.qtpl:157
	qw422016.N().S(`	} else {
		Logf("T`)
//line template.qtpl:159
	qw422016.N().D(line + 15)
//line template.qtpl:159
	qw422016.N().S(`: `)
//line template.qtpl:159
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:159
	qw422016.N().S(`: Noo!")
	}
	`)
//line template.qtpl:161
	if retCtype != "" {
//line template.qtpl:161
		qw422016.N().S(`return cRet`)
//line template.qtpl:161
	}
//line template.qtpl:161
	qw422016.N().S(`
}
`)
//line template.qtpl:163
}

//line template.qtpl:163
func WriteGoCallback(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl, baseName string) {
//line template.qtpl:163
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:163
	StreamGoCallback(qw422016, line, m, baseName)
//line template.qtpl:163
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:163
}

//line template.qtpl:163
func GoCallback(line int, m *parser.MethodDecl, baseName string) string {
//line template.qtpl:163
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:163
	WriteGoCallback(qb422016, line, m, baseName)
//line template.qtpl:163
	qs422016 := string(qb422016.B)
//line template.qtpl:163
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:163
	return qs422016
//line template.qtpl:163
}

//line template.qtpl:165
func StreamGoBindFunc(qw422016 *qt422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:165
	qw422016.N().S(`
`)
//line template.qtpl:167
	goName := st.Common().GoName()
	baseName := st.Common().BaseName()
	self := baseName

//line template.qtpl:169
	qw422016.N().S(`func (`)
//line template.qtpl:170
	qw422016.E().S(self)
//line template.qtpl:170
	qw422016.N().S(` *`)
//line template.qtpl:170
	qw422016.E().S(goName)
//line template.qtpl:170
	qw422016.N().S(`) Bind(a interface{}) *`)
//line template.qtpl:170
	qw422016.E().S(goName)
//line template.qtpl:170
	qw422016.N().S(` {
	cefingoIfaceAccess.Lock()
	defer cefingoIfaceAccess.Unlock()
`)
//line template.qtpl:173
	funcnum := 0

//line template.qtpl:174
	for _, m := range st.Methods {
//line template.qtpl:175
		if !m.IsGetFunc() {
//line template.qtpl:175
			qw422016.N().S(`
`)
//line template.qtpl:176
			if funcnum == 0 {
//line template.qtpl:176
				qw422016.N().S(`	cp := `)
//line template.qtpl:177
				qw422016.E().S(self)
//line template.qtpl:177
				qw422016.N().S(`.p_`)
//line template.qtpl:177
				qw422016.E().S(baseName)
//line template.qtpl:177
				qw422016.N().S(`

`)
//line template.qtpl:179
			}
//line template.qtpl:180
			funcnum += 1

//line template.qtpl:180
			qw422016.N().S(`	if h, ok := a.(`)
//line template.qtpl:181
			qw422016.E().S(m.IfName())
//line template.qtpl:181
			qw422016.N().S(`); ok {
		`)
//line template.qtpl:182
			qw422016.E().S(baseName)
//line template.qtpl:182
			qw422016.N().S(`_handlers.`)
//line template.qtpl:182
			streammemberName(qw422016, m)
//line template.qtpl:182
			qw422016.N().S(`[cp] = h
	}
`)
//line template.qtpl:184
		}
//line template.qtpl:184
	}
//line template.qtpl:184
	qw422016.N().S(`
	if accessor, ok := a.(`)
//line template.qtpl:185
	qw422016.E().S(goName)
//line template.qtpl:185
	qw422016.N().S(`Accessor); ok {
		accessor.Set`)
//line template.qtpl:186
	qw422016.E().S(goName)
//line template.qtpl:186
	qw422016.N().S(`(`)
//line template.qtpl:186
	qw422016.E().S(self)
//line template.qtpl:186
	qw422016.N().S(`)
		Logf("T`)
//line template.qtpl:187
	qw422016.N().D((line + funcnum*4) + 22)
//line template.qtpl:187
	qw422016.N().S(`:")
	}

	return `)
//line template.qtpl:190
	qw422016.E().S(self)
//line template.qtpl:190
	qw422016.N().S(`
}
`)
//line template.qtpl:192
}

//line template.qtpl:192
func WriteGoBindFunc(qq422016 qtio422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:192
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:192
	StreamGoBindFunc(qw422016, line, st)
//line template.qtpl:192
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:192
}

//line template.qtpl:192
func GoBindFunc(line int, st *parser.StructDecl) string {
//line template.qtpl:192
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:192
	WriteGoBindFunc(qb422016, line, st)
//line template.qtpl:192
	qs422016 := string(qb422016.B)
//line template.qtpl:192
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:192
	return qs422016
//line template.qtpl:192
}

//line template.qtpl:194
func StreamGoGetFunc(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:194
	qw422016.N().S(`
//export cefingo_`)
//line template.qtpl:195
	qw422016.E().S(baseName)
//line template.qtpl:195
	qw422016.N().S(`_`)
//line template.qtpl:195
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:195
	qw422016.N().S(`
func cefingo_`)
//line template.qtpl:196
	qw422016.E().S(baseName)
//line template.qtpl:196
	qw422016.N().S(`_`)
//line template.qtpl:196
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:196
	qw422016.N().S(`(self *C.`)
//line template.qtpl:196
	qw422016.E().S(cName)
//line template.qtpl:196
	qw422016.N().S(`) (ch `)
//line template.qtpl:196
	qw422016.E().S(m.ReturnType().GoCType())
//line template.qtpl:196
	qw422016.N().S(`) {
	cefingoIfaceAccess.Lock()
	defer cefingoIfaceAccess.Unlock()

	handler := `)
//line template.qtpl:200
	qw422016.E().S(baseName)
//line template.qtpl:200
	qw422016.N().S(`_handlers.`)
//line template.qtpl:200
	qw422016.E().S(memberName(m))
//line template.qtpl:200
	qw422016.N().S(`[self]
	if handler == nil {
		Logf("T`)
//line template.qtpl:202
	qw422016.N().D(line + 9)
//line template.qtpl:202
	qw422016.N().S(`: `)
//line template.qtpl:202
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:202
	qw422016.N().S(`")
	} else {
		BaseAddRef(handler.p_`)
//line template.qtpl:204
	qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:204
	qw422016.N().S(`)
		ch = handler.p_`)
//line template.qtpl:205
	qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:205
	qw422016.N().S(`
	}
	return ch
}
`)
//line template.qtpl:209
}

//line template.qtpl:209
func WriteGoGetFunc(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:209
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:209
	StreamGoGetFunc(qw422016, line, m, goName, baseName, cName)
//line template.qtpl:209
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:209
}

//line template.qtpl:209
func GoGetFunc(line int, m *parser.MethodDecl, goName, baseName, cName string) string {
//line template.qtpl:209
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:209
	WriteGoGetFunc(qb422016, line, m, goName, baseName, cName)
//line template.qtpl:209
	qs422016 := string(qb422016.B)
//line template.qtpl:209
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:209
	return qs422016
//line template.qtpl:209
}

//line template.qtpl:211
func StreamAssocGetFunc(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:211
	qw422016.N().S(`
func (`)
//line template.qtpl:212
	qw422016.E().S(baseName)
//line template.qtpl:212
	qw422016.N().S(` *`)
//line template.qtpl:212
	qw422016.E().S(goName)
//line template.qtpl:212
	qw422016.N().S(`) Assoc`)
//line template.qtpl:212
	qw422016.E().S(m.ReturnType().TitleCase())
//line template.qtpl:212
	qw422016.N().S(`(handler `)
//line template.qtpl:212
	qw422016.E().S(m.ReturnType().GoType())
//line template.qtpl:212
	qw422016.N().S(`) {
	cp := `)
//line template.qtpl:213
	qw422016.E().S(baseName)
//line template.qtpl:213
	qw422016.N().S(`.p_`)
//line template.qtpl:213
	qw422016.E().S(baseName)
//line template.qtpl:213
	qw422016.N().S(`
	cefingoIfaceAccess.Lock()
	defer cefingoIfaceAccess.Unlock()

	`)
//line template.qtpl:217
	qw422016.E().S(baseName)
//line template.qtpl:217
	qw422016.N().S(`_handlers.`)
//line template.qtpl:217
	streammemberName(qw422016, m)
//line template.qtpl:217
	qw422016.N().S(`[cp] = handler
}
`)
//line template.qtpl:219
}

//line template.qtpl:219
func WriteAssocGetFunc(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:219
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:219
	StreamAssocGetFunc(qw422016, line, m, goName, baseName, cName)
//line template.qtpl:219
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:219
}

//line template.qtpl:219
func AssocGetFunc(line int, m *parser.MethodDecl, goName, baseName, cName string) string {
//line template.qtpl:219
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:219
	WriteAssocGetFunc(qb422016, line, m, goName, baseName, cName)
//line template.qtpl:219
	qs422016 := string(qb422016.B)
//line template.qtpl:219
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:219
	return qs422016
//line template.qtpl:219
}

//line template.qtpl:221
func StreamGoHead(qw422016 *qt422016.Writer, useRuntime, useSync, useTime, useUnsafe, defMutex bool) {
//line template.qtpl:221
	qw422016.N().S(`
// Code generated by "gen-cefingo.go" DO NOT EDIT.
package capi

import (
`)
//line template.qtpl:226
	if useRuntime {
//line template.qtpl:226
		qw422016.N().S(`	"runtime"
`)
//line template.qtpl:227
	}
//line template.qtpl:228
	if useSync {
//line template.qtpl:228
		qw422016.N().S(`	"sync"
`)
//line template.qtpl:229
	}
//line template.qtpl:230
	if useTime {
//line template.qtpl:230
		qw422016.N().S(`	"time"
`)
//line template.qtpl:231
	}
//line template.qtpl:232
	if useUnsafe {
//line template.qtpl:232
		qw422016.N().S(`	"unsafe"
`)
//line template.qtpl:233
	}
//line template.qtpl:233
	qw422016.N().S(`)
// #include "cefingo.h"
import "C"
`)
//line template.qtpl:237
	if defMutex {
//line template.qtpl:237
		qw422016.N().S(`var cefingoIfaceAccess sync.Mutex
`)
//line template.qtpl:238
	}
//line template.qtpl:239
}

//line template.qtpl:239
func WriteGoHead(qq422016 qtio422016.Writer, useRuntime, useSync, useTime, useUnsafe, defMutex bool) {
//line template.qtpl:239
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:239
	StreamGoHead(qw422016, useRuntime, useSync, useTime, useUnsafe, defMutex)
//line template.qtpl:239
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:239
}

//line template.qtpl:239
func GoHead(useRuntime, useSync, useTime, useUnsafe, defMutex bool) string {
//line template.qtpl:239
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:239
	WriteGoHead(qb422016, useRuntime, useSync, useTime, useUnsafe, defMutex)
//line template.qtpl:239
	qs422016 := string(qb422016.B)
//line template.qtpl:239
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:239
	return qs422016
//line template.qtpl:239
}

//line template.qtpl:241
func StreamGoIface(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:241
	qw422016.N().S(`
`)
//line template.qtpl:242
	StreamMethodComments(qw422016, m, &line)
//line template.qtpl:242
	qw422016.N().S(`type `)
//line template.qtpl:243
	qw422016.E().S(m.IfName())
//line template.qtpl:243
	qw422016.N().S(` interface {
	`)
//line template.qtpl:244
	qw422016.E().S(m.Funcname.TitleCase())
//line template.qtpl:244
	qw422016.N().S(` (
`)
//line template.qtpl:245
	for _, p := range m.Params() {
//line template.qtpl:246
		if !(p.IsSliceLengthParam() || p.IsByteSliceLengthParam() || p.IsOutParam()) {
//line template.qtpl:246
			qw422016.N().S(`		`)
//line template.qtpl:247
			qw422016.E().S(goParamName(p))
//line template.qtpl:247
			qw422016.N().S(` `)
//line template.qtpl:247
			qw422016.E().S(p.GoTypeIn())
//line template.qtpl:247
			qw422016.N().S(`,
`)
//line template.qtpl:248
		}
//line template.qtpl:249
	}
//line template.qtpl:249
	qw422016.N().S(`	) `)
//line template.qtpl:250
	qw422016.E().S(retTypes(m))
//line template.qtpl:250
	qw422016.N().S(`
}
`)
//line template.qtpl:252
}

//line template.qtpl:252
func WriteGoIface(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:252
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:252
	StreamGoIface(qw422016, line, m)
//line template.qtpl:252
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:252
}

//line template.qtpl:252
func GoIface(line int, m *parser.MethodDecl) string {
//line template.qtpl:252
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:252
	WriteGoIface(qb422016, line, m)
//line template.qtpl:252
	qs422016 := string(qb422016.B)
//line template.qtpl:252
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:252
	return qs422016
//line template.qtpl:252
}

//line template.qtpl:254
func streammemberName(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:255
	if m.IsGetFunc() {
//line template.qtpl:256
		qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:257
	} else {
//line template.qtpl:258
		qw422016.E().S(m.Funcname.Name())
//line template.qtpl:258
		qw422016.N().S(`_handler`)
//line template.qtpl:258
		qw422016.E().S("")
//line template.qtpl:259
	}
//line template.qtpl:260
}

//line template.qtpl:260
func writememberName(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:260
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:260
	streammemberName(qw422016, m)
//line template.qtpl:260
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:260
}

//line template.qtpl:260
func memberName(m *parser.MethodDecl) string {
//line template.qtpl:260
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:260
	writememberName(qb422016, m)
//line template.qtpl:260
	qs422016 := string(qb422016.B)
//line template.qtpl:260
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:260
	return qs422016
//line template.qtpl:260
}

//line template.qtpl:262
func streammemberGoType(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:263
	if m.IsGetFunc() {
//line template.qtpl:264
		qw422016.E().S(m.ReturnType().GoType())
//line template.qtpl:265
	} else {
//line template.qtpl:266
		qw422016.E().S(m.IfName())
//line template.qtpl:267
	}
//line template.qtpl:268
}

//line template.qtpl:268
func writememberGoType(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:268
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:268
	streammemberGoType(qw422016, m)
//line template.qtpl:268
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:268
}

//line template.qtpl:268
func memberGoType(m *parser.MethodDecl) string {
//line template.qtpl:268
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:268
	writememberGoType(qb422016, m)
//line template.qtpl:268
	qs422016 := string(qb422016.B)
//line template.qtpl:268
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:268
	return qs422016
//line template.qtpl:268
}

//line template.qtpl:270
func StreamIfaceStruct(qw422016 *qt422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:270
	qw422016.N().S(`
var `)
//line template.qtpl:271
	qw422016.E().S(st.BaseName())
//line template.qtpl:271
	qw422016.N().S(`_handlers = struct {
`)
//line template.qtpl:272
	for _, m := range st.Methods {
//line template.qtpl:272
		qw422016.N().S(`	`)
//line template.qtpl:273
		streammemberName(qw422016, m)
//line template.qtpl:273
		qw422016.N().S(` map[*C.`)
//line template.qtpl:273
		qw422016.E().S(st.Name())
//line template.qtpl:273
		qw422016.N().S(`]`)
//line template.qtpl:273
		streammemberGoType(qw422016, m)
//line template.qtpl:273
		qw422016.N().S(`
`)
//line template.qtpl:274
	}
//line template.qtpl:274
	qw422016.N().S(`}{
`)
//line template.qtpl:276
	for _, m := range st.Methods {
//line template.qtpl:276
		qw422016.N().S(`	map[*C.`)
//line template.qtpl:277
		qw422016.E().S(st.Name())
//line template.qtpl:277
		qw422016.N().S(`]`)
//line template.qtpl:277
		streammemberGoType(qw422016, m)
//line template.qtpl:277
		qw422016.N().S(`{},
`)
//line template.qtpl:278
	}
//line template.qtpl:278
	qw422016.N().S(`}
`)
//line template.qtpl:280
}

//line template.qtpl:280
func WriteIfaceStruct(qq422016 qtio422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:280
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:280
	StreamIfaceStruct(qw422016, line, st)
//line template.qtpl:280
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:280
}

//line template.qtpl:280
func IfaceStruct(line int, st *parser.StructDecl) string {
//line template.qtpl:280
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:280
	WriteIfaceStruct(qb422016, line, st)
//line template.qtpl:280
	qs422016 := string(qb422016.B)
//line template.qtpl:280
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:280
	return qs422016
//line template.qtpl:280
}

//line template.qtpl:282
func StreamGoAllocFunc(qw422016 *qt422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:282
	qw422016.N().S(`
// Alloc`)
//line template.qtpl:283
	qw422016.E().S(st.GoName())
//line template.qtpl:283
	qw422016.N().S(` allocates `)
//line template.qtpl:283
	qw422016.E().S(st.GoName())
//line template.qtpl:283
	qw422016.N().S(` and construct it
func Alloc`)
//line template.qtpl:284
	qw422016.E().S(st.GoName())
//line template.qtpl:284
	qw422016.N().S(`() *`)
//line template.qtpl:284
	qw422016.E().S(st.GoName())
//line template.qtpl:284
	qw422016.N().S(` {
	up := c_calloc(1, C.sizeof_cefingo_`)
//line template.qtpl:285
	qw422016.E().S(st.BaseName())
//line template.qtpl:285
	qw422016.N().S(`_wrapper_t, "T`)
//line template.qtpl:285
	qw422016.N().D(line + 4)
//line template.qtpl:285
	qw422016.N().S(`:")
	cefp := C.cefingo_construct_`)
//line template.qtpl:286
	qw422016.E().S(st.BaseName())
//line template.qtpl:286
	qw422016.N().S(`((*C.cefingo_`)
//line template.qtpl:286
	qw422016.E().S(st.BaseName())
//line template.qtpl:286
	qw422016.N().S(`_wrapper_t)(up))

	registerDeassocer(up, DeassocFunc(func() {
		// Do not have reference to `)
//line template.qtpl:289
	qw422016.E().S(st.Name())
//line template.qtpl:289
	qw422016.N().S(` itself in DeassocFunc,
		// or `)
//line template.qtpl:290
	qw422016.E().S(st.Name())
//line template.qtpl:290
	qw422016.N().S(` is never GCed.
		Tracef(up, "T`)
//line template.qtpl:291
	qw422016.N().D(line + 10)
//line template.qtpl:291
	qw422016.N().S(`:")

		cefingoIfaceAccess.Lock()
		defer cefingoIfaceAccess.Unlock()
`)
//line template.qtpl:295
	for _, m := range st.Methods {
//line template.qtpl:295
		qw422016.N().S(`		delete(`)
//line template.qtpl:296
		qw422016.E().S(st.BaseName())
//line template.qtpl:296
		qw422016.N().S(`_handlers.`)
//line template.qtpl:296
		streammemberName(qw422016, m)
//line template.qtpl:296
		qw422016.N().S(`, cefp)
`)
//line template.qtpl:297
	}
//line template.qtpl:297
	qw422016.N().S(`	}))

	return new`)
//line template.qtpl:300
	qw422016.E().S(st.GoName())
//line template.qtpl:300
	qw422016.N().S(`(cefp)
}
`)
//line template.qtpl:302
}

//line template.qtpl:302
func WriteGoAllocFunc(qq422016 qtio422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:302
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:302
	StreamGoAllocFunc(qw422016, line, st)
//line template.qtpl:302
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:302
}

//line template.qtpl:302
func GoAllocFunc(line int, st *parser.StructDecl) string {
//line template.qtpl:302
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:302
	WriteGoAllocFunc(qb422016, line, st)
//line template.qtpl:302
	qs422016 := string(qb422016.B)
//line template.qtpl:302
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:302
	return qs422016
//line template.qtpl:302
}

//line template.qtpl:304
func streammethodCTypeName(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:305
	callee := strings.Replace(m.CalleeName(), "::", "_", 1)

//line template.qtpl:305
	qw422016.N().S(`T_`)
//line template.qtpl:306
	qw422016.E().S(strings.ToUpper(callee))
//line template.qtpl:307
}

//line template.qtpl:307
func writemethodCTypeName(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:307
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:307
	streammethodCTypeName(qw422016, m)
//line template.qtpl:307
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:307
}

//line template.qtpl:307
func methodCTypeName(m *parser.MethodDecl) string {
//line template.qtpl:307
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:307
	writemethodCTypeName(qb422016, m)
//line template.qtpl:307
	qs422016 := string(qb422016.B)
//line template.qtpl:307
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:307
	return qs422016
//line template.qtpl:307
}

//line template.qtpl:309
func streamconstructorName(qw422016 *qt422016.Writer, st *parser.StructDecl) {
//line template.qtpl:310
	qw422016.E().S(st.Name() + " *cefingo_construct_" + st.BaseName() + "(cefingo_" + st.BaseName() + "_wrapper_t* " + st.BaseName() + ")")
//line template.qtpl:311
}

//line template.qtpl:311
func writeconstructorName(qq422016 qtio422016.Writer, st *parser.StructDecl) {
//line template.qtpl:311
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:311
	streamconstructorName(qw422016, st)
//line template.qtpl:311
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:311
}

//line template.qtpl:311
func constructorName(st *parser.StructDecl) string {
//line template.qtpl:311
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:311
	writeconstructorName(qb422016, st)
//line template.qtpl:311
	qs422016 := string(qb422016.B)
//line template.qtpl:311
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:311
	return qs422016
//line template.qtpl:311
}

//line template.qtpl:313
func StreamCConstruct(qw422016 *qt422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:313
	qw422016.N().S(`
`)
//line template.qtpl:314
	for _, m := range st.Methods {
//line template.qtpl:315
		if m.HasConstParams() {
//line template.qtpl:315
			qw422016.N().S(`typedef `)
//line template.qtpl:316
			qw422016.E().S(m.ReturnType().CType())
//line template.qtpl:316
			qw422016.N().S(` (*`)
//line template.qtpl:317
			qw422016.E().S(methodCTypeName(m))
//line template.qtpl:317
			qw422016.N().S(`)(
`)
//line template.qtpl:318
			for i, p := range m.Params() {
//line template.qtpl:319
				if i > 0 {
//line template.qtpl:319
					qw422016.N().S(`, 
`)
//line template.qtpl:320
				}
//line template.qtpl:320
				qw422016.N().S(`	`)
//line template.qtpl:320
				qw422016.E().S(p.CType())
//line template.qtpl:321
			}
//line template.qtpl:321
			qw422016.N().S(`
);
`)
//line template.qtpl:323
		}
//line template.qtpl:324
	}
//line template.qtpl:324
	qw422016.N().S(`
`)
//line template.qtpl:326
	qw422016.E().S(constructorName(st))
//line template.qtpl:326
	qw422016.N().S(`
{
	initialize_cefingo_base_ref_counted(
		offsetof(__typeof__(*`)
//line template.qtpl:329
	qw422016.E().S(st.BaseName())
//line template.qtpl:329
	qw422016.N().S(`), counter),
		(cef_base_ref_counted_t*) `)
//line template.qtpl:330
	qw422016.E().S(st.BaseName())
//line template.qtpl:330
	qw422016.N().S(`);
	
	// callbacks
`)
//line template.qtpl:333
	for _, m := range st.Methods {
//line template.qtpl:333
		qw422016.N().S(`	`)
//line template.qtpl:334
		qw422016.E().S(st.BaseName())
//line template.qtpl:334
		qw422016.N().S(`->body.`)
//line template.qtpl:334
		qw422016.E().S(m.Funcname.Name())
//line template.qtpl:334
		qw422016.N().S(` = `)
//line template.qtpl:334
		if m.HasConstParams() {
//line template.qtpl:334
			qw422016.N().S(`(`)
//line template.qtpl:334
			qw422016.E().S(methodCTypeName(m))
//line template.qtpl:334
			qw422016.N().S(`)`)
//line template.qtpl:334
		}
//line template.qtpl:334
		qw422016.N().S(`
		cefingo_`)
//line template.qtpl:335
		qw422016.E().S(st.BaseName())
//line template.qtpl:335
		qw422016.N().S(`_`)
//line template.qtpl:335
		qw422016.E().S(m.Funcname.Name())
//line template.qtpl:335
		qw422016.N().S(`;
`)
//line template.qtpl:336
	}
//line template.qtpl:336
	qw422016.N().S(`
	return (`)
//line template.qtpl:338
	qw422016.E().S(st.Name())
//line template.qtpl:338
	qw422016.N().S(`*)`)
//line template.qtpl:338
	qw422016.E().S(st.BaseName())
//line template.qtpl:338
	qw422016.N().S(`;
}
`)
//line template.qtpl:340
}

//line template.qtpl:340
func WriteCConstruct(qq422016 qtio422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:340
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:340
	StreamCConstruct(qw422016, line, st)
//line template.qtpl:340
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:340
}

//line template.qtpl:340
func CConstruct(line int, st *parser.StructDecl) string {
//line template.qtpl:340
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:340
	WriteCConstruct(qb422016, line, st)
//line template.qtpl:340
	qs422016 := string(qb422016.B)
//line template.qtpl:340
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:340
	return qs422016
//line template.qtpl:340
}

//line template.qtpl:342
func StreamHCallback(qw422016 *qt422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:342
	qw422016.N().S(`
CEFINGO_REF_COUNTER_WRAPPER(cef_`)
//line template.qtpl:343
	qw422016.E().S(st.BaseName())
//line template.qtpl:343
	qw422016.N().S(`_t, cefingo_`)
//line template.qtpl:343
	qw422016.E().S(st.BaseName())
//line template.qtpl:343
	qw422016.N().S(`_wrapper_t);
extern `)
//line template.qtpl:344
	qw422016.E().S(constructorName(st))
//line template.qtpl:344
	qw422016.N().S(`;
`)
//line template.qtpl:345
}

//line template.qtpl:345
func WriteHCallback(qq422016 qtio422016.Writer, line int, st *parser.StructDecl) {
//line template.qtpl:345
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:345
	StreamHCallback(qw422016, line, st)
//line template.qtpl:345
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:345
}

//line template.qtpl:345
func HCallback(line int, st *parser.StructDecl) string {
//line template.qtpl:345
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:345
	WriteHCallback(qb422016, line, st)
//line template.qtpl:345
	qs422016 := string(qb422016.B)
//line template.qtpl:345
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:345
	return qs422016
//line template.qtpl:345
}

//line template.qtpl:347
func streampreConvToC(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:348
	if p.IsOutParam() {
//line template.qtpl:349
		if ok, argLen := p.IsByteSliceParam(); ok {
//line template.qtpl:349
			qw422016.N().S(`	`)
//line template.qtpl:350
			qw422016.E().S(argLen)
//line template.qtpl:350
			qw422016.N().S(` := len(`)
//line template.qtpl:350
			qw422016.E().S(goParamName(p))
//line template.qtpl:350
			qw422016.N().S(`)
	`)
//line template.qtpl:351
			qw422016.E().S(cTempName(p))
//line template.qtpl:351
			qw422016.N().S(` := c_calloc(1, C.size_t(`)
//line template.qtpl:351
			qw422016.E().S(argLen)
//line template.qtpl:351
			qw422016.N().S(`), "T`)
//line template.qtpl:351
			qw422016.N().D(*line)
//line template.qtpl:351
			qw422016.N().S(`:`)
//line template.qtpl:351
			qw422016.E().S(p.CalleeName() + "::" + p.Name())
//line template.qtpl:351
			qw422016.N().S(`")
`)
//line template.qtpl:352
		} else if p.Type().Ty == parser.TyStringT {
//line template.qtpl:352
			qw422016.N().S(`	`)
//line template.qtpl:353
			qw422016.E().S(cTempName(p))
//line template.qtpl:353
			qw422016.N().S(` := create_cef_string("")
	defer clear_cef_string(`)
//line template.qtpl:354
			qw422016.E().S(cTempName(p))
//line template.qtpl:354
			qw422016.N().S(`)
`)
//line template.qtpl:355
		} else {
//line template.qtpl:355
			qw422016.N().S(`	var `)
//line template.qtpl:356
			qw422016.E().S(cTempName(p))
//line template.qtpl:356
			qw422016.N().S(` `)
//line template.qtpl:356
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:356
			qw422016.N().S(`
`)
//line template.qtpl:357
		}
//line template.qtpl:358
	} else if ok, argLen := p.IsByteSliceParam(); ok && !p.IsInOutParam() {
//line template.qtpl:358
		qw422016.N().S(`	`)
//line template.qtpl:359
		qw422016.E().S(argLen)
//line template.qtpl:359
		qw422016.N().S(` := len(`)
//line template.qtpl:359
		qw422016.E().S(goParamName(p))
//line template.qtpl:359
		qw422016.N().S(`)
	`)
//line template.qtpl:360
		qw422016.E().S(cTempName(p))
//line template.qtpl:360
		qw422016.N().S(` := C.CBytes(`)
//line template.qtpl:360
		qw422016.E().S(goParamName(p))
//line template.qtpl:360
		qw422016.N().S(`)
`)
//line template.qtpl:361
	} else if ok, argLen := p.IsSliceParam(); ok {
//line template.qtpl:361
		qw422016.N().S(`	`)
//line template.qtpl:362
		qw422016.E().S(argLen)
//line template.qtpl:362
		qw422016.N().S(` := len(`)
//line template.qtpl:362
		qw422016.E().S(goParamName(p))
//line template.qtpl:362
		qw422016.N().S(`)
	`)
//line template.qtpl:363
		qw422016.E().S(cTempName(p))
//line template.qtpl:363
		qw422016.N().S(` := c_calloc(C.size_t(`)
//line template.qtpl:363
		qw422016.E().S(argLen)
//line template.qtpl:363
		qw422016.N().S(`), (C.size_t)(unsafe.Sizeof(`)
//line template.qtpl:363
		streamgoParamName(qw422016, p)
//line template.qtpl:363
		qw422016.N().S(`[0])), "T`)
//line template.qtpl:363
		qw422016.N().D(*line)
//line template.qtpl:363
		qw422016.N().S(`:`)
//line template.qtpl:363
		qw422016.E().S(p.CalleeName() + "::" + p.Name())
//line template.qtpl:363
		qw422016.N().S(`")
	slice := (*[1 << 30]`)
//line template.qtpl:364
		qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:364
		qw422016.N().S(`)(`)
//line template.qtpl:364
		qw422016.E().S(cTempName(p))
//line template.qtpl:364
		qw422016.N().S(`)[:`)
//line template.qtpl:364
		qw422016.E().S(argLen)
//line template.qtpl:364
		qw422016.N().S(`:`)
//line template.qtpl:364
		qw422016.E().S(argLen)
//line template.qtpl:364
		qw422016.N().S(`]
	for i, v := range `)
//line template.qtpl:365
		qw422016.E().S(goParamName(p))
//line template.qtpl:365
		qw422016.N().S(` {
		cefp := v.p_`)
//line template.qtpl:366
		qw422016.E().S(p.Type().BaseName())
//line template.qtpl:366
		qw422016.N().S(`
		if cefp != nil {
			BaseAddRef(cefp)
		}
		slice[i] = cefp
	}
`)
//line template.qtpl:372
	} else if p.Type().IsRefCountedClass() {
//line template.qtpl:372
		qw422016.N().S(`	var `)
//line template.qtpl:373
		streamgoTempName(qw422016, p)
//line template.qtpl:373
		qw422016.N().S(` `)
//line template.qtpl:373
		qw422016.E().S(p.GoCType())
//line template.qtpl:373
		qw422016.N().S(` 
	if `)
//line template.qtpl:374
		streamgoParamName(qw422016, p)
//line template.qtpl:374
		qw422016.N().S(` != nil {
		`)
//line template.qtpl:375
		streamgoTempName(qw422016, p)
//line template.qtpl:375
		qw422016.N().S(` = `)
//line template.qtpl:375
		qw422016.E().S(goParamName(p))
//line template.qtpl:375
		qw422016.N().S(`.p_`)
//line template.qtpl:375
		qw422016.E().S(p.Type().BaseName())
//line template.qtpl:375
		qw422016.N().S(`
		BaseAddRef(`)
//line template.qtpl:376
		streamgoTempName(qw422016, p)
//line template.qtpl:376
		qw422016.N().S(`)
	}
`)
//line template.qtpl:378
	} else {
//line template.qtpl:379
		switch p.GoType() {
//line template.qtpl:380
		case "bool":
//line template.qtpl:381
			*line += 4

//line template.qtpl:381
			qw422016.N().S(`	var `)
//line template.qtpl:382
			qw422016.E().S(cTempName(p))
//line template.qtpl:382
			qw422016.N().S(` int
	if `)
//line template.qtpl:383
			qw422016.E().S(goParamName(p))
//line template.qtpl:383
			qw422016.N().S(` {
		`)
//line template.qtpl:384
			qw422016.E().S(cTempName(p))
//line template.qtpl:384
			qw422016.N().S(` = 1
	}
`)
//line template.qtpl:386
		case "string":
//line template.qtpl:387
			*line += 2

//line template.qtpl:387
			qw422016.N().S(`	`)
//line template.qtpl:388
			qw422016.E().S(cName(p))
//line template.qtpl:388
			qw422016.N().S(` := create_cef_string(`)
//line template.qtpl:388
			qw422016.E().S(goParamName(p))
//line template.qtpl:388
			qw422016.N().S(`)
	defer clear_cef_string(`)
//line template.qtpl:389
			qw422016.E().S(cName(p))
//line template.qtpl:389
			qw422016.N().S(`)
`)
//line template.qtpl:390
		case "time.Time":
//line template.qtpl:391
			*line += 1

//line template.qtpl:391
			qw422016.N().S(`	`)
//line template.qtpl:392
			qw422016.E().S(cName(p))
//line template.qtpl:392
			qw422016.N().S(` := `)
//line template.qtpl:392
			qw422016.E().S(goParamName(p))
//line template.qtpl:392
			qw422016.N().S(`.Unix()
`)
//line template.qtpl:393
		}
//line template.qtpl:394
	}
//line template.qtpl:395
}

//line template.qtpl:395
func writepreConvToC(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:395
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:395
	streampreConvToC(qw422016, p, line)
//line template.qtpl:395
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:395
}

//line template.qtpl:395
func preConvToC(p parser.Param, line *int) string {
//line template.qtpl:395
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:395
	writepreConvToC(qb422016, p, line)
//line template.qtpl:395
	qs422016 := string(qb422016.B)
//line template.qtpl:395
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:395
	return qs422016
//line template.qtpl:395
}

//line template.qtpl:397
func streamcName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:398
	switch p.Type().GoType() {
//line template.qtpl:399
	case "string", "*time.Time", "time.Time":
//line template.qtpl:399
		qw422016.N().S(`c_`)
//line template.qtpl:400
	}
//line template.qtpl:400
	qw422016.E().S(goParamName(p))
//line template.qtpl:401
}

//line template.qtpl:401
func writecName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:401
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:401
	streamcName(qw422016, p)
//line template.qtpl:401
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:401
}

//line template.qtpl:401
func cName(p parser.Param) string {
//line template.qtpl:401
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:401
	writecName(qb422016, p)
//line template.qtpl:401
	qs422016 := string(qb422016.B)
//line template.qtpl:401
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:401
	return qs422016
//line template.qtpl:401
}

//line template.qtpl:403
func streamcTempName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:403
	qw422016.N().S(`tmp`)
//line template.qtpl:404
	streamcName(qw422016, p)
//line template.qtpl:405
}

//line template.qtpl:405
func writecTempName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:405
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:405
	streamcTempName(qw422016, p)
//line template.qtpl:405
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:405
}

//line template.qtpl:405
func cTempName(p parser.Param) string {
//line template.qtpl:405
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:405
	writecTempName(qb422016, p)
//line template.qtpl:405
	qs422016 := string(qb422016.B)
//line template.qtpl:405
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:405
	return qs422016
//line template.qtpl:405
}

//line template.qtpl:407
func streamconvToC(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:408
	if p.IsOutParam() {
//line template.qtpl:409
		if ok, _ := p.IsByteSliceParam(); ok {
//line template.qtpl:410
			qw422016.N().S(cTempName(p))
//line template.qtpl:411
		} else if p.Type().Ty == parser.TyStringT {
//line template.qtpl:412
			qw422016.N().S(cTempName(p))
//line template.qtpl:413
		} else {
//line template.qtpl:414
			qw422016.N().S("&" + cTempName(p))
//line template.qtpl:415
		}
//line template.qtpl:416
	} else if p.IsRefCountedClass() {
//line template.qtpl:417
		if p.Name() == "self" {
//line template.qtpl:417
			qw422016.N().S(`self.p_`)
//line template.qtpl:417
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:418
		} else {
//line template.qtpl:418
			qw422016.E().S(goTempName(p))
//line template.qtpl:418
		}
//line template.qtpl:419
	} else if p.IsScopedClass() {
//line template.qtpl:420
		qw422016.E().S(cName(p))
//line template.qtpl:420
		qw422016.N().S(`.p_`)
//line template.qtpl:420
		qw422016.E().S(p.Type().BaseName())
//line template.qtpl:421
	} else if ok, _ := p.IsByteSliceParam(); ok && !p.IsInOutParam() {
//line template.qtpl:422
		qw422016.N().S(cTempName(p))
//line template.qtpl:423
	} else if ok, _ := p.IsSliceParam(); ok {
//line template.qtpl:423
		qw422016.N().S(`	(`)
//line template.qtpl:424
		qw422016.E().S(p.GoCType())
//line template.qtpl:424
		qw422016.N().S(`)(`)
//line template.qtpl:424
		streamcTempName(qw422016, p)
//line template.qtpl:424
		qw422016.E().S(")")
//line template.qtpl:425
	} else {
//line template.qtpl:426
		switch p.GoType() {
//line template.qtpl:427
		case "bool":
//line template.qtpl:428
			qw422016.E().S(p.GoCType())
//line template.qtpl:428
			qw422016.N().S(`(`)
//line template.qtpl:428
			qw422016.E().S(cTempName(p) + ")")
//line template.qtpl:429
		case "*time.Time":
//line template.qtpl:430
			qw422016.N().S("&" + cName(p))
//line template.qtpl:431
		case "time.Time":
//line template.qtpl:432
			qw422016.E().S("C.time_t(" + cName(p) + ")")
//line template.qtpl:433
		case "unsafe.Pointer":
//line template.qtpl:433
			log.Printf("T335: %s::%s\n", p.CalleeName(), p.Name())

//line template.qtpl:434
			qw422016.E().S(cName(p))
//line template.qtpl:435
		default:
//line template.qtpl:436
			qw422016.E().S("(" + p.GoCType() + ")(")
//line template.qtpl:436
			qw422016.E().S(cName(p))
//line template.qtpl:436
			qw422016.E().S(")")
//line template.qtpl:437
		}
//line template.qtpl:438
	}
//line template.qtpl:439
}

//line template.qtpl:439
func writeconvToC(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:439
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:439
	streamconvToC(qw422016, p)
//line template.qtpl:439
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:439
}

//line template.qtpl:439
func convToC(p parser.Param) string {
//line template.qtpl:439
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:439
	writeconvToC(qb422016, p)
//line template.qtpl:439
	qs422016 := string(qb422016.B)
//line template.qtpl:439
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:439
	return qs422016
//line template.qtpl:439
}

//line template.qtpl:441
func streampostConvFromC(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:442
	if p.IsOutParam() {
//line template.qtpl:443
		if ok, argLen := p.IsByteSliceParam(); ok {
//line template.qtpl:443
			qw422016.N().S(`	`)
//line template.qtpl:444
			qw422016.E().S(goParamName(p))
//line template.qtpl:444
			qw422016.N().S(` = C.GoBytes(`)
//line template.qtpl:444
			qw422016.E().S(cTempName(p))
//line template.qtpl:444
			qw422016.N().S(`, C.int(`)
//line template.qtpl:444
			qw422016.E().S(argLen)
//line template.qtpl:444
			qw422016.N().S(`))
	C.free(`)
//line template.qtpl:445
			qw422016.E().S(cTempName(p))
//line template.qtpl:445
			qw422016.N().S(`)
`)
//line template.qtpl:446
		} else if p.Type().Ty == parser.TyStringT {
//line template.qtpl:446
			qw422016.N().S(`	`)
//line template.qtpl:447
			qw422016.E().S(goParamName(p))
//line template.qtpl:447
			qw422016.N().S(` = string_from_cef_string(`)
//line template.qtpl:447
			qw422016.E().S(cTempName(p))
//line template.qtpl:447
			qw422016.N().S(`)
`)
//line template.qtpl:448
		} else if p.Type().Deref().IsRefCountedClass() {
//line template.qtpl:448
			qw422016.N().S(`	`)
//line template.qtpl:449
			qw422016.E().S(goParamName(p))
//line template.qtpl:449
			qw422016.N().S(` = new`)
//line template.qtpl:449
			qw422016.E().S(p.Type().Deref().Deref().GoType())
//line template.qtpl:449
			qw422016.N().S(`(`)
//line template.qtpl:449
			qw422016.E().S(cTempName(p))
//line template.qtpl:449
			qw422016.N().S(`)
`)
//line template.qtpl:450
		} else if p.Type().Ty == parser.TyTimeT {
//line template.qtpl:450
			qw422016.N().S(`
	`)
//line template.qtpl:451
			qw422016.E().S(goParamName(p))
//line template.qtpl:451
			qw422016.N().S(` = time.Unix(int64(`)
//line template.qtpl:451
			streamcTempName(qw422016, p)
//line template.qtpl:451
			qw422016.N().S(`), 0)
`)
//line template.qtpl:452
		} else {
//line template.qtpl:452
			qw422016.N().S(`	`)
//line template.qtpl:453
			qw422016.E().S(goParamName(p))
//line template.qtpl:453
			qw422016.N().S(` = (`)
//line template.qtpl:453
			qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:453
			qw422016.N().S(`)(`)
//line template.qtpl:453
			qw422016.E().S(cTempName(p))
//line template.qtpl:453
			qw422016.N().S(`)
`)
//line template.qtpl:454
		}
//line template.qtpl:455
	} else if ok, _ := p.IsByteSliceParam(); ok && !p.IsInOutParam() {
//line template.qtpl:455
		qw422016.N().S(`	C.free(`)
//line template.qtpl:456
		qw422016.E().S(cTempName(p))
//line template.qtpl:456
		qw422016.N().S(`)
`)
//line template.qtpl:457
	}
//line template.qtpl:458
}

//line template.qtpl:458
func writepostConvFromC(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:458
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:458
	streampostConvFromC(qw422016, p, line)
//line template.qtpl:458
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:458
}

//line template.qtpl:458
func postConvFromC(p parser.Param, line *int) string {
//line template.qtpl:458
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:458
	writepostConvFromC(qb422016, p, line)
//line template.qtpl:458
	qs422016 := string(qb422016.B)
//line template.qtpl:458
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:458
	return qs422016
//line template.qtpl:458
}

//line template.qtpl:460
func StreamGoFunction(qw422016 *qt422016.Writer, line int, f *parser.FuncDecl) {
//line template.qtpl:460
	qw422016.N().S(`func `)
//line template.qtpl:461
	qw422016.E().S(f.Funcname.TitleCase())
//line template.qtpl:461
	qw422016.N().S(`(
`)
//line template.qtpl:462
	for _, p := range f.Params() {
//line template.qtpl:463
		if !p.IsByteSliceLengthParam() && !p.IsOutParam() {
//line template.qtpl:463
			qw422016.N().S(`	`)
//line template.qtpl:464
			qw422016.E().S(goParamName(p))
//line template.qtpl:464
			qw422016.N().S(` `)
//line template.qtpl:464
			qw422016.E().S(p.GoType())
//line template.qtpl:464
			qw422016.N().S(`,
`)
//line template.qtpl:465
		}
//line template.qtpl:466
	}
//line template.qtpl:466
	qw422016.N().S(`) `)
//line template.qtpl:467
	streamretTypes(qw422016, f)
//line template.qtpl:467
	qw422016.N().S(`{
`)
//line template.qtpl:468
	for _, p := range f.Params() {
//line template.qtpl:469
		if exp := preConvToC(p, &line); exp != "" {
//line template.qtpl:470
			qw422016.N().S(exp)
//line template.qtpl:471
		}
//line template.qtpl:472
	}
//line template.qtpl:472
	qw422016.N().S(`
	`)
//line template.qtpl:473
	if f.HasReturnValue() {
//line template.qtpl:473
		qw422016.N().S(`cRet := `)
//line template.qtpl:473
	}
//line template.qtpl:473
	qw422016.N().S(`C.`)
//line template.qtpl:473
	qw422016.E().S(f.Name())
//line template.qtpl:473
	qw422016.N().S(`(`)
//line template.qtpl:473
	for i, p := range f.Params() {
//line template.qtpl:474
		if i > 0 {
//line template.qtpl:474
			qw422016.N().S(`, `)
//line template.qtpl:474
		}
//line template.qtpl:474
		streamconvToC(qw422016, p)
//line template.qtpl:475
	}
//line template.qtpl:475
	qw422016.N().S(`)

`)
//line template.qtpl:477
	for _, p := range f.Params() {
//line template.qtpl:477
		qw422016.E().S(postConvFromC(p, &line))
//line template.qtpl:477
	}
//line template.qtpl:477
	qw422016.N().S(`	`)
//line template.qtpl:478
	streamgoReturnStmt(qw422016, f)
//line template.qtpl:478
	qw422016.N().S(`
}
`)
//line template.qtpl:480
}

//line template.qtpl:480
func WriteGoFunction(qq422016 qtio422016.Writer, line int, f *parser.FuncDecl) {
//line template.qtpl:480
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:480
	StreamGoFunction(qw422016, line, f)
//line template.qtpl:480
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:480
}

//line template.qtpl:480
func GoFunction(line int, f *parser.FuncDecl) string {
//line template.qtpl:480
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:480
	WriteGoFunction(qb422016, line, f)
//line template.qtpl:480
	qs422016 := string(qb422016.B)
//line template.qtpl:480
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:480
	return qs422016
//line template.qtpl:480
}

// Generate Go func Return Types

//line template.qtpl:483
func streamretTypes(qw422016 *qt422016.Writer, m parser.Callable) {
//line template.qtpl:484
	if m.HasReturnValue() || m.HasOutParam() {
//line template.qtpl:484
		qw422016.N().S(`(`)
//line template.qtpl:485
		if m.HasReturnValue() {
//line template.qtpl:485
			qw422016.N().S(`ret `)
//line template.qtpl:485
			qw422016.E().S(m.ReturnGoType())
//line template.qtpl:485
			qw422016.N().S(`,`)
//line template.qtpl:485
		}
//line template.qtpl:486
		for _, p := range m.Params() {
//line template.qtpl:487
			if p.IsOutParam() || p.IsInOutParam() {
//line template.qtpl:488
				qw422016.E().S(goParamNameOut(p))
//line template.qtpl:488
				qw422016.N().S(` `)
//line template.qtpl:488
				if p.Type().Ty == parser.TyStringT && p.Type().Pointer == 1 {
//line template.qtpl:489
					qw422016.E().S(p.Type().GoType())
//line template.qtpl:489
				} else {
//line template.qtpl:489
					qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:489
				}
//line template.qtpl:489
				qw422016.N().S(`, `)
//line template.qtpl:490
			}
//line template.qtpl:491
		}
//line template.qtpl:492
		qw422016.E().S(")")
//line template.qtpl:493
	}
//line template.qtpl:494
}

//line template.qtpl:494
func writeretTypes(qq422016 qtio422016.Writer, m parser.Callable) {
//line template.qtpl:494
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:494
	streamretTypes(qw422016, m)
//line template.qtpl:494
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:494
}

//line template.qtpl:494
func retTypes(m parser.Callable) string {
//line template.qtpl:494
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:494
	writeretTypes(qb422016, m)
//line template.qtpl:494
	qs422016 := string(qb422016.B)
//line template.qtpl:494
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:494
	return qs422016
//line template.qtpl:494
}

// Generate Go method call to object method (self->method(...))

//line template.qtpl:497
func StreamCefObjectMethod(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:497
	qw422016.N().S(`
`)
//line template.qtpl:498
	for _, c := range m.Comment {
//line template.qtpl:499
		qw422016.E().S(c)
//line template.qtpl:499
		qw422016.N().S(`
`)
//line template.qtpl:500
	}
//line template.qtpl:500
	qw422016.N().S(`func  (`)
//line template.qtpl:501
	qw422016.E().S(goParamName(m.Params()[0]))
//line template.qtpl:501
	qw422016.N().S(` `)
//line template.qtpl:501
	qw422016.E().S(m.Params()[0].GoType())
//line template.qtpl:501
	qw422016.N().S(`) `)
//line template.qtpl:501
	qw422016.E().S(m.Funcname.TitleCase())
//line template.qtpl:501
	qw422016.N().S(`(
`)
//line template.qtpl:502
	for i, p := range m.Params() {
//line template.qtpl:503
		if i > 0 && !p.IsOutParam() {
//line template.qtpl:504
			if !p.IsByteSliceLengthParam() && !p.IsSliceLengthParam() {
//line template.qtpl:504
				qw422016.N().S(`	`)
//line template.qtpl:505
				qw422016.E().S(goParamName(p))
//line template.qtpl:505
				qw422016.N().S(` `)
//line template.qtpl:505
				qw422016.E().S(p.GoType())
//line template.qtpl:505
				qw422016.N().S(`,
`)
//line template.qtpl:506
			}
//line template.qtpl:507
		}
//line template.qtpl:508
	}
//line template.qtpl:508
	qw422016.N().S(`) `)
//line template.qtpl:509
	streamretTypes(qw422016, m)
//line template.qtpl:509
	qw422016.N().S(`{
`)
//line template.qtpl:510
	for i, p := range m.Params() {
//line template.qtpl:511
		if !(i == 0 && p.Name() == "self") {
//line template.qtpl:512
			if stmts := preConvToC(p, &line); stmts != "" {
//line template.qtpl:513
				qw422016.N().S(stmts)
//line template.qtpl:514
			}
//line template.qtpl:515
		}
//line template.qtpl:516
	}
//line template.qtpl:516
	qw422016.N().S(`
	`)
//line template.qtpl:517
	if m.HasReturnValue() {
//line template.qtpl:517
		qw422016.N().S(`cRet := `)
//line template.qtpl:517
	}
//line template.qtpl:517
	qw422016.N().S(`C.`)
//line template.qtpl:517
	qw422016.E().S(methodCName(m))
//line template.qtpl:517
	qw422016.N().S(`(`)
//line template.qtpl:517
	for i, p := range m.Params() {
//line template.qtpl:518
		if i > 0 {
//line template.qtpl:518
			qw422016.N().S(`, `)
//line template.qtpl:518
		}
//line template.qtpl:518
		streamconvToC(qw422016, p)
//line template.qtpl:519
	}
//line template.qtpl:519
	qw422016.N().S(`)

`)
//line template.qtpl:521
	for _, p := range m.Params() {
//line template.qtpl:521
		qw422016.E().S(postConvFromC(p, &line))
//line template.qtpl:521
	}
//line template.qtpl:521
	qw422016.N().S(`	`)
//line template.qtpl:522
	streamgoReturnStmt(qw422016, m)
//line template.qtpl:522
	qw422016.N().S(`
}
`)
//line template.qtpl:524
}

//line template.qtpl:524
func WriteCefObjectMethod(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:524
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:524
	StreamCefObjectMethod(qw422016, line, m)
//line template.qtpl:524
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:524
}

//line template.qtpl:524
func CefObjectMethod(line int, m *parser.MethodDecl) string {
//line template.qtpl:524
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:524
	WriteCefObjectMethod(qb422016, line, m)
//line template.qtpl:524
	qs422016 := string(qb422016.B)
//line template.qtpl:524
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:524
	return qs422016
//line template.qtpl:524
}

//line template.qtpl:526
func streamgoReturnStmt(qw422016 *qt422016.Writer, m parser.Callable) {
//line template.qtpl:527
	if m.HasReturnValue() {
//line template.qtpl:528
		if m.IsBoolValueMethod() {
//line template.qtpl:528
			qw422016.N().S(`
	ret = cRet == 1
`)
//line template.qtpl:530
		} else if m.ReturnType().Ty == parser.TyStringUserfreeT {
//line template.qtpl:530
			qw422016.N().S(`
	s := string_from_cef_string((*C.cef_string_t)(cRet))
	if cRet != nil {
		C.cef_string_userfree_free(cRet)
	}
	ret = s
`)
//line template.qtpl:536
		} else {
//line template.qtpl:536
			qw422016.N().S(`
	ret = `)
//line template.qtpl:537
			qw422016.E().S(ConvToGoTypeExp(m.ReturnType(), "cRet"))
//line template.qtpl:537
			qw422016.N().S(`
`)
//line template.qtpl:538
		}
//line template.qtpl:539
	}
//line template.qtpl:540
	if m.HasReturnValue() || m.HasOutParam() {
//line template.qtpl:540
		first := true

//line template.qtpl:540
		qw422016.N().S(`	return `)
//line template.qtpl:541
		if m.HasReturnValue() {
//line template.qtpl:541
			qw422016.N().S(`ret`)
//line template.qtpl:541
			first = false

//line template.qtpl:541
		}
//line template.qtpl:542
		for _, p := range m.Params() {
//line template.qtpl:543
			if p.IsOutParam() || p.IsInOutParam() {
//line template.qtpl:544
				if !first {
//line template.qtpl:544
					qw422016.N().S(`, `)
//line template.qtpl:544
				}
//line template.qtpl:544
				qw422016.E().S(goParamName(p))
//line template.qtpl:544
				first = false

//line template.qtpl:545
			}
//line template.qtpl:546
		}
//line template.qtpl:547
	}
//line template.qtpl:548
}

//line template.qtpl:548
func writegoReturnStmt(qq422016 qtio422016.Writer, m parser.Callable) {
//line template.qtpl:548
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:548
	streamgoReturnStmt(qw422016, m)
//line template.qtpl:548
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:548
}

//line template.qtpl:548
func goReturnStmt(m parser.Callable) string {
//line template.qtpl:548
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:548
	writegoReturnStmt(qb422016, m)
//line template.qtpl:548
	qs422016 := string(qb422016.B)
//line template.qtpl:548
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:548
	return qs422016
//line template.qtpl:548
}

//line template.qtpl:550
func streammethodCName(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:551
	qw422016.E().S("cefingo_" + m.ClassBaseName() + "_" + m.Funcname.Name())
//line template.qtpl:552
}

//line template.qtpl:552
func writemethodCName(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:552
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:552
	streammethodCName(qw422016, m)
//line template.qtpl:552
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:552
}

//line template.qtpl:552
func methodCName(m *parser.MethodDecl) string {
//line template.qtpl:552
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:552
	writemethodCName(qb422016, m)
//line template.qtpl:552
	qs422016 := string(qb422016.B)
//line template.qtpl:552
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:552
	return qs422016
//line template.qtpl:552
}

//line template.qtpl:554
func streammethodCSig(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:555
	qw422016.E().S(m.ReturnType().CType())
//line template.qtpl:555
	qw422016.N().S(` `)
//line template.qtpl:555
	qw422016.E().S(methodCName(m))
//line template.qtpl:555
	qw422016.N().S(`(
`)
//line template.qtpl:556
	for i, p := range m.Params() {
//line template.qtpl:557
		if i > 0 {
//line template.qtpl:557
			qw422016.N().S(`,
`)
//line template.qtpl:558
		}
//line template.qtpl:558
		qw422016.N().S(`	`)
//line template.qtpl:559
		qw422016.E().S(p.CType())
//line template.qtpl:559
		qw422016.N().S(` `)
//line template.qtpl:559
		qw422016.E().S(p.Name())
//line template.qtpl:560
	}
//line template.qtpl:560
	qw422016.N().S(`
`)
//line template.qtpl:561
	qw422016.E().S(")")
//line template.qtpl:562
}

//line template.qtpl:562
func writemethodCSig(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:562
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:562
	streammethodCSig(qw422016, m)
//line template.qtpl:562
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:562
}

//line template.qtpl:562
func methodCSig(m *parser.MethodDecl) string {
//line template.qtpl:562
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:562
	writemethodCSig(qb422016, m)
//line template.qtpl:562
	qs422016 := string(qb422016.B)
//line template.qtpl:562
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:562
	return qs422016
//line template.qtpl:562
}

//line template.qtpl:564
func StreamCefObjectMethodH(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:564
	qw422016.N().S(`
extern `)
//line template.qtpl:565
	qw422016.E().S(methodCSig(m))
//line template.qtpl:565
	qw422016.N().S(`;
`)
//line template.qtpl:566
}

//line template.qtpl:566
func WriteCefObjectMethodH(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:566
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:566
	StreamCefObjectMethodH(qw422016, m)
//line template.qtpl:566
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:566
}

//line template.qtpl:566
func CefObjectMethodH(m *parser.MethodDecl) string {
//line template.qtpl:566
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:566
	WriteCefObjectMethodH(qb422016, m)
//line template.qtpl:566
	qs422016 := string(qb422016.B)
//line template.qtpl:566
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:566
	return qs422016
//line template.qtpl:566
}

//line template.qtpl:568
func StreamCefObjectMethodC(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:568
	qw422016.N().S(`
`)
//line template.qtpl:569
	retGoType := m.ReturnGoType()

//line template.qtpl:570
	qw422016.E().S(methodCSig(m))
//line template.qtpl:570
	qw422016.N().S(`
{
	`)
//line template.qtpl:572
	if retGoType != "" {
//line template.qtpl:572
		qw422016.N().S(`return `)
//line template.qtpl:572
	}
//line template.qtpl:572
	qw422016.N().S(`self->`)
//line template.qtpl:572
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:572
	qw422016.N().S(`(
`)
//line template.qtpl:573
	for i, p := range m.Params() {
//line template.qtpl:574
		if i > 0 {
//line template.qtpl:574
			qw422016.N().S(`, 
`)
//line template.qtpl:575
		}
//line template.qtpl:575
		qw422016.N().S(`		`)
//line template.qtpl:576
		qw422016.E().S(p.Name())
//line template.qtpl:577
	}
//line template.qtpl:577
	qw422016.N().S(`
	);
}
`)
//line template.qtpl:580
}

//line template.qtpl:580
func WriteCefObjectMethodC(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:580
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:580
	StreamCefObjectMethodC(qw422016, m)
//line template.qtpl:580
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:580
}

//line template.qtpl:580
func CefObjectMethodC(m *parser.MethodDecl) string {
//line template.qtpl:580
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:580
	WriteCefObjectMethodC(qb422016, m)
//line template.qtpl:580
	qs422016 := string(qb422016.B)
//line template.qtpl:580
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:580
	return qs422016
//line template.qtpl:580
}

// newCXxxxT()

//line template.qtpl:583
func StreamGoType(qw422016 *qt422016.Writer, d *parser.StructDecl, line int) {
//line template.qtpl:583
	qw422016.N().S(`
`)
//line template.qtpl:584
	goName := d.Token().GoName()
	cName := d.Token().Name()
	typeName := d.Token().BaseName()
	line = line + 25

//line template.qtpl:588
	qw422016.N().S(`// Go type for `)
//line template.qtpl:589
	qw422016.E().S(cName)
//line template.qtpl:589
	qw422016.N().S(`	
type `)
//line template.qtpl:590
	qw422016.E().S(goName)
//line template.qtpl:590
	qw422016.N().S(` struct {
	noCopy noCopy
	p_`)
//line template.qtpl:592
	qw422016.E().S(typeName)
//line template.qtpl:592
	qw422016.N().S(` *C.`)
//line template.qtpl:592
	qw422016.E().S(cName)
//line template.qtpl:592
	qw422016.N().S(`
}

type RefTo`)
//line template.qtpl:595
	qw422016.E().S(goName)
//line template.qtpl:595
	qw422016.N().S(` struct {
	p_`)
//line template.qtpl:596
	qw422016.E().S(typeName)
//line template.qtpl:596
	qw422016.N().S(` *`)
//line template.qtpl:596
	qw422016.E().S(goName)
//line template.qtpl:596
	qw422016.N().S(`
}

type `)
//line template.qtpl:599
	qw422016.E().S(goName)
//line template.qtpl:599
	qw422016.N().S(`Accessor interface {
	Get`)
//line template.qtpl:600
	qw422016.E().S(goName)
//line template.qtpl:600
	qw422016.N().S(`() *`)
//line template.qtpl:600
	qw422016.E().S(goName)
//line template.qtpl:600
	qw422016.N().S(`
	Set`)
//line template.qtpl:601
	qw422016.E().S(goName)
//line template.qtpl:601
	qw422016.N().S(`(*`)
//line template.qtpl:601
	qw422016.E().S(goName)
//line template.qtpl:601
	qw422016.N().S(`)
}

func (r RefTo`)
//line template.qtpl:604
	qw422016.E().S(goName)
//line template.qtpl:604
	qw422016.N().S(`) Get`)
//line template.qtpl:604
	qw422016.E().S(goName)
//line template.qtpl:604
	qw422016.N().S(`() *`)
//line template.qtpl:604
	qw422016.E().S(goName)
//line template.qtpl:604
	qw422016.N().S(` {
	return r.p_`)
//line template.qtpl:605
	qw422016.E().S(typeName)
//line template.qtpl:605
	qw422016.N().S(`
}

func (r *RefTo`)
//line template.qtpl:608
	qw422016.E().S(goName)
//line template.qtpl:608
	qw422016.N().S(`) Set`)
//line template.qtpl:608
	qw422016.E().S(goName)
//line template.qtpl:608
	qw422016.N().S(`(p *`)
//line template.qtpl:608
	qw422016.E().S(goName)
//line template.qtpl:608
	qw422016.N().S(`) {
	r.p_`)
//line template.qtpl:609
	qw422016.E().S(typeName)
//line template.qtpl:609
	qw422016.N().S(` = p
}

// Go type `)
//line template.qtpl:612
	qw422016.E().S(goName)
//line template.qtpl:612
	qw422016.N().S(` wraps cef type *C.`)
//line template.qtpl:612
	qw422016.E().S(cName)
//line template.qtpl:612
	qw422016.N().S(`
func new`)
//line template.qtpl:613
	qw422016.E().S(goName)
//line template.qtpl:613
	qw422016.N().S(`(p *C.`)
//line template.qtpl:613
	qw422016.E().S(cName)
//line template.qtpl:613
	qw422016.N().S(`) *`)
//line template.qtpl:613
	qw422016.E().S(goName)
//line template.qtpl:613
	qw422016.N().S(` {
	if p == nil {
		return nil
	}
	Tracef(unsafe.Pointer(p), "T`)
//line template.qtpl:617
	qw422016.N().D(line + 4)
//line template.qtpl:617
	qw422016.N().S(`:")
`)
//line template.qtpl:618
	if d.St == parser.StRefCounted {
//line template.qtpl:618
		qw422016.N().S(`	BaseAddRef(p)
`)
//line template.qtpl:620
	}
//line template.qtpl:620
	qw422016.N().S(`	go_`)
//line template.qtpl:621
	qw422016.E().S(typeName)
//line template.qtpl:621
	qw422016.N().S(` := `)
//line template.qtpl:621
	qw422016.E().S(goName)
//line template.qtpl:621
	qw422016.N().S(`{noCopy{}, p}
`)
//line template.qtpl:622
	if d.St == parser.StRefCounted {
//line template.qtpl:622
		qw422016.N().S(`	runtime.SetFinalizer(&go_`)
//line template.qtpl:623
		qw422016.E().S(typeName)
//line template.qtpl:623
		qw422016.N().S(`, func(g *`)
//line template.qtpl:623
		qw422016.E().S(goName)
//line template.qtpl:623
		qw422016.N().S(`) {
		Tracef(unsafe.Pointer(g.p_`)
//line template.qtpl:624
		qw422016.E().S(typeName)
//line template.qtpl:624
		qw422016.N().S(`), "T`)
//line template.qtpl:624
		qw422016.N().D(line + 8)
//line template.qtpl:624
		qw422016.N().S(`:")
		BaseRelease(g.p_`)
//line template.qtpl:625
		qw422016.E().S(typeName)
//line template.qtpl:625
		qw422016.N().S(`)
	})
`)
//line template.qtpl:627
	}
//line template.qtpl:627
	qw422016.N().S(`	return &go_`)
//line template.qtpl:628
	qw422016.E().S(typeName)
//line template.qtpl:628
	qw422016.N().S(`
}
`)
//line template.qtpl:630
	if d.St == parser.StRefCounted {
//line template.qtpl:630
		qw422016.N().S(`// *C.`)
//line template.qtpl:631
		qw422016.E().S(cName)
//line template.qtpl:631
		qw422016.N().S(` has refCounted interface
func (`)
//line template.qtpl:632
		qw422016.E().S(typeName)
//line template.qtpl:632
		qw422016.N().S(` *`)
//line template.qtpl:632
		qw422016.E().S(goName)
//line template.qtpl:632
		qw422016.N().S(`) HasOneRef() bool {
	return BaseHasOneRef(`)
//line template.qtpl:633
		qw422016.E().S(typeName)
//line template.qtpl:633
		qw422016.N().S(`.p_`)
//line template.qtpl:633
		qw422016.E().S(typeName)
//line template.qtpl:633
		qw422016.N().S(`)
}

func (p *C.`)
//line template.qtpl:636
		qw422016.E().S(cName)
//line template.qtpl:636
		qw422016.N().S(`) cast_to_p_base_ref_counted_t() *C.cef_base_ref_counted_t {
	return (*C.cef_base_ref_counted_t)(unsafe.Pointer(p))
}
`)
//line template.qtpl:639
	}
//line template.qtpl:640
}

//line template.qtpl:640
func WriteGoType(qq422016 qtio422016.Writer, d *parser.StructDecl, line int) {
//line template.qtpl:640
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:640
	StreamGoType(qw422016, d, line)
//line template.qtpl:640
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:640
}

//line template.qtpl:640
func GoType(d *parser.StructDecl, line int) string {
//line template.qtpl:640
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:640
	WriteGoType(qb422016, d, line)
//line template.qtpl:640
	qs422016 := string(qb422016.B)
//line template.qtpl:640
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:640
	return qs422016
//line template.qtpl:640
}
