// Code generated by qtc from "template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template.qtpl:1
package main

//line template.qtpl:2
import (
	"log"
	"strings"

	"github.com/turutcrane/cefingo/tools/gen-cefingo/parser"
)

// Generate parameter name for Go func.

//line template.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template.qtpl:10
func streamgoParamName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:11
	switch p.Name() {
//line template.qtpl:12
	case "type", "string", "map", "time", "range":
//line template.qtpl:13
		qw422016.E().S("c" + p.Name())
//line template.qtpl:14
	default:
//line template.qtpl:15
		qw422016.E().S(p.Name())
//line template.qtpl:16
	}
//line template.qtpl:17
}

//line template.qtpl:17
func writegoParamName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:17
	streamgoParamName(qw422016, p)
//line template.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:17
}

//line template.qtpl:17
func goParamName(p parser.Param) string {
//line template.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:17
	writegoParamName(qb422016, p)
//line template.qtpl:17
	qs422016 := string(qb422016.B)
//line template.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:17
	return qs422016
//line template.qtpl:17
}

// Generate parameter name for Go func.

//line template.qtpl:20
func streamgoParamNameOut(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:21
	streamgoParamName(qw422016, p)
//line template.qtpl:22
	if p.IsInOutParam() {
//line template.qtpl:22
		qw422016.N().S(`Out`)
//line template.qtpl:22
	}
//line template.qtpl:23
}

//line template.qtpl:23
func writegoParamNameOut(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:23
	streamgoParamNameOut(qw422016, p)
//line template.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:23
}

//line template.qtpl:23
func goParamNameOut(p parser.Param) string {
//line template.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:23
	writegoParamNameOut(qb422016, p)
//line template.qtpl:23
	qs422016 := string(qb422016.B)
//line template.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:23
	return qs422016
//line template.qtpl:23
}

//line template.qtpl:25
func streamgoTempName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:25
	qw422016.N().S(`goTmp`)
//line template.qtpl:26
	qw422016.E().S(p.Name())
//line template.qtpl:27
}

//line template.qtpl:27
func writegoTempName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:27
	streamgoTempName(qw422016, p)
//line template.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:27
}

//line template.qtpl:27
func goTempName(p parser.Param) string {
//line template.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:27
	writegoTempName(qb422016, p)
//line template.qtpl:27
	qs422016 := string(qb422016.B)
//line template.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:27
	return qs422016
//line template.qtpl:27
}

//line template.qtpl:29
func streamgoTempNameOut(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:30
	qw422016.E().S(goTempName(p) + "Out")
//line template.qtpl:31
}

//line template.qtpl:31
func writegoTempNameOut(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:31
	streamgoTempNameOut(qw422016, p)
//line template.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:31
}

//line template.qtpl:31
func goTempNameOut(p parser.Param) string {
//line template.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:31
	writegoTempNameOut(qb422016, p)
//line template.qtpl:31
	qs422016 := string(qb422016.B)
//line template.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:31
	return qs422016
//line template.qtpl:31
}

// Statemens to convert from C.param to Go type.

//line template.qtpl:34
func streamconvToGoTypeStmts(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:35
	if p.IsInOutParam() {
//line template.qtpl:36
		if p.Type().Ty == parser.TyStringT {
//line template.qtpl:36
			qw422016.N().S(`		`)
//line template.qtpl:37
			streamgoTempName(qw422016, p)
//line template.qtpl:37
			qw422016.N().S(` := string_from_cef_string(`)
//line template.qtpl:37
			qw422016.E().S(goParamName(p))
//line template.qtpl:37
			qw422016.N().S(`)
`)
//line template.qtpl:38
		} else if p.Type().Pointer == 2 && p.Type().Deref().IsRefCountedClass() {
//line template.qtpl:38
			qw422016.N().S(`		`)
//line template.qtpl:39
			streamgoTempName(qw422016, p)
//line template.qtpl:39
			qw422016.N().S(` := `)
//line template.qtpl:39
			qw422016.E().S(ConvToGoTypeExp(p.Type().Deref(), "*"+goParamName(p)))
//line template.qtpl:39
			*line += 1

//line template.qtpl:39
			qw422016.N().S(`
		cefp := `)
//line template.qtpl:40
			qw422016.E().S(goTempName(p))
//line template.qtpl:40
			qw422016.N().S(`.p_`)
//line template.qtpl:40
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:40
			qw422016.N().S(`
`)
//line template.qtpl:41
		} else if p.Type().Ty == parser.TyStructSimple || p.Type().Ty == parser.TyInt {
//line template.qtpl:41
			qw422016.N().S(`		`)
//line template.qtpl:42
			streamgoTempName(qw422016, p)
//line template.qtpl:42
			qw422016.N().S(` := `)
//line template.qtpl:42
			qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:42
			qw422016.N().S(`(*`)
//line template.qtpl:42
			qw422016.E().S(p.Name())
//line template.qtpl:42
			qw422016.N().S(`)
`)
//line template.qtpl:43
		} else {
//line template.qtpl:44
			log.Panicf("E43: %s::%s::%s", p.CalleeName(), p.Name(), p.Type())

//line template.qtpl:45
		}
//line template.qtpl:46
	} else if !p.IsOutParam() {
//line template.qtpl:47
		if bs, maxLenArg := p.IsByteSliceParam(); bs {
//line template.qtpl:47
			qw422016.N().S(`		`)
//line template.qtpl:48
			streamgoTempName(qw422016, p)
//line template.qtpl:48
			qw422016.N().S(` := (*[1 << 30]byte)(`)
//line template.qtpl:48
			qw422016.E().S(p.Name())
//line template.qtpl:48
			qw422016.N().S(`)[:`)
//line template.qtpl:48
			qw422016.E().S(maxLenArg)
//line template.qtpl:48
			qw422016.N().S(`:`)
//line template.qtpl:48
			qw422016.E().S(maxLenArg)
//line template.qtpl:48
			qw422016.N().S(`]`)
//line template.qtpl:48
			*line += 1

//line template.qtpl:48
			qw422016.N().S(`
`)
//line template.qtpl:49
		} else if s, maxLenArg := p.IsSliceParam(); s {
//line template.qtpl:49
			qw422016.N().S(`		slice := (*[1 << 30](`)
//line template.qtpl:50
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:50
			qw422016.N().S(`))(unsafe.Pointer(`)
//line template.qtpl:50
			qw422016.E().S(p.Name())
//line template.qtpl:50
			qw422016.N().S(`))[:`)
//line template.qtpl:50
			qw422016.E().S(maxLenArg)
//line template.qtpl:50
			qw422016.N().S(`:`)
//line template.qtpl:50
			qw422016.E().S(maxLenArg)
//line template.qtpl:50
			qw422016.N().S(`]
		`)
//line template.qtpl:51
			streamgoTempName(qw422016, p)
//line template.qtpl:51
			qw422016.N().S(` := make(`)
//line template.qtpl:51
			qw422016.E().S(p.GoType())
//line template.qtpl:51
			qw422016.N().S(`, `)
//line template.qtpl:51
			qw422016.E().S(maxLenArg)
//line template.qtpl:51
			qw422016.N().S(`)
		for i, v := range slice {
			`)
//line template.qtpl:53
			streamgoTempName(qw422016, p)
//line template.qtpl:53
			qw422016.N().S(`[i] = new`)
//line template.qtpl:53
			qw422016.E().S(p.Type().Deref().Deref().GoType())
//line template.qtpl:53
			qw422016.N().S(`(v)
		}
`)
//line template.qtpl:55
		} else {
//line template.qtpl:56
			if !p.IsSliceLengthParam() {
//line template.qtpl:56
				qw422016.N().S(`		`)
//line template.qtpl:57
				streamgoTempName(qw422016, p)
//line template.qtpl:57
				qw422016.N().S(` := `)
//line template.qtpl:57
				qw422016.E().S(ConvToGoTypeExp(p.Type(), goParamName(p)))
//line template.qtpl:57
				*line += 1

//line template.qtpl:57
				qw422016.N().S(`
`)
//line template.qtpl:58
			}
//line template.qtpl:59
		}
//line template.qtpl:60
	}
//line template.qtpl:61
}

//line template.qtpl:61
func writeconvToGoTypeStmts(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:61
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:61
	streamconvToGoTypeStmts(qw422016, p, line)
//line template.qtpl:61
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:61
}

//line template.qtpl:61
func convToGoTypeStmts(p parser.Param, line *int) string {
//line template.qtpl:61
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:61
	writeconvToGoTypeStmts(qb422016, p, line)
//line template.qtpl:61
	qs422016 := string(qb422016.B)
//line template.qtpl:61
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:61
	return qs422016
//line template.qtpl:61
}

// Set returned Go value to C.param and cleanup

//line template.qtpl:64
func streampostProcess(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:65
	if p.IsOutParam() {
//line template.qtpl:66
		if p.Type().Ty == parser.TyStringT {
//line template.qtpl:66
			qw422016.N().S(`		set_cef_string(`)
//line template.qtpl:67
			streamgoParamName(qw422016, p)
//line template.qtpl:67
			qw422016.N().S(`, `)
//line template.qtpl:67
			streamgoTempNameOut(qw422016, p)
//line template.qtpl:67
			qw422016.N().S(`)`)
//line template.qtpl:67
			*line += 1

//line template.qtpl:67
			qw422016.N().S(`
`)
//line template.qtpl:68
		} else if p.Type().Deref().IsRefCountedClass() {
//line template.qtpl:68
			qw422016.N().S(`		if `)
//line template.qtpl:69
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:69
			qw422016.N().S(` != nil {
			*`)
//line template.qtpl:70
			qw422016.E().S(goParamName(p))
//line template.qtpl:70
			qw422016.N().S(` = `)
//line template.qtpl:70
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:70
			qw422016.N().S(`.p_`)
//line template.qtpl:70
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:70
			qw422016.N().S(`
			BaseAddRef(*`)
//line template.qtpl:71
			qw422016.E().S(goParamName(p))
//line template.qtpl:71
			qw422016.N().S(`)
		}`)
//line template.qtpl:72
			*line += 4

//line template.qtpl:72
			qw422016.N().S(`
`)
//line template.qtpl:73
		} else if isSlice, sliceLen := p.IsByteSliceParam(); isSlice {
//line template.qtpl:73
			qw422016.N().S(`		*`)
//line template.qtpl:74
			qw422016.E().S(sliceLen)
//line template.qtpl:74
			qw422016.N().S(` = (C.size_t)(len(`)
//line template.qtpl:74
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:74
			qw422016.N().S(`))
		*`)
//line template.qtpl:75
			qw422016.E().S(goParamName(p))
//line template.qtpl:75
			qw422016.N().S(` = (`)
//line template.qtpl:75
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:75
			qw422016.N().S(`)(C.calloc(1, C.size_t(len(`)
//line template.qtpl:75
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:75
			qw422016.N().S(`))))
		target := (*[1<<30]byte)(unsafe.Pointer(*`)
//line template.qtpl:76
			qw422016.E().S(goParamName(p))
//line template.qtpl:76
			qw422016.N().S(`))[:*`)
//line template.qtpl:76
			qw422016.E().S(sliceLen)
//line template.qtpl:76
			qw422016.N().S(`:*`)
//line template.qtpl:76
			qw422016.E().S(sliceLen)
//line template.qtpl:76
			qw422016.N().S(`]
		copy(target, `)
//line template.qtpl:77
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:77
			qw422016.N().S(`)
`)
//line template.qtpl:78
		} else if isSlice, _ := p.IsSliceParam(); isSlice {
//line template.qtpl:78
			qw422016.N().S(`		`)
//line template.qtpl:79
			log.Panicf("T76: Not implemented %v", p)

//line template.qtpl:79
			qw422016.N().S(`
`)
//line template.qtpl:80
		} else if p.IsBoolParam() {
//line template.qtpl:80
			qw422016.N().S(`		*`)
//line template.qtpl:81
			qw422016.E().S(goParamName(p))
//line template.qtpl:81
			qw422016.N().S(` = 0
		if `)
//line template.qtpl:82
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:82
			qw422016.N().S(` {
			*`)
//line template.qtpl:83
			qw422016.E().S(goParamName(p))
//line template.qtpl:83
			qw422016.N().S(` = 1
		}
`)
//line template.qtpl:85
		} else {
//line template.qtpl:85
			qw422016.N().S(`		*`)
//line template.qtpl:86
			qw422016.E().S(goParamName(p))
//line template.qtpl:86
			qw422016.N().S(` = (`)
//line template.qtpl:86
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:86
			qw422016.N().S(`)(`)
//line template.qtpl:86
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:86
			qw422016.N().S(`)`)
//line template.qtpl:86
			*line += 1

//line template.qtpl:86
			qw422016.N().S(`
`)
//line template.qtpl:87
		}
//line template.qtpl:88
	} else if p.IsInOutParam() {
//line template.qtpl:89
		if p.Type().Ty == parser.TyStringT {
//line template.qtpl:89
			qw422016.N().S(`		set_cef_string(`)
//line template.qtpl:90
			qw422016.E().S(goParamName(p))
//line template.qtpl:90
			qw422016.N().S(`,`)
//line template.qtpl:90
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:90
			qw422016.N().S(`)`)
//line template.qtpl:90
			*line += 1

//line template.qtpl:90
			qw422016.N().S(`
`)
//line template.qtpl:91
		} else if p.Type().Ty == parser.TyStructSimple || p.Type().Ty == parser.TyInt {
//line template.qtpl:91
			qw422016.N().S(`		*`)
//line template.qtpl:92
			qw422016.E().S(p.Name())
//line template.qtpl:92
			qw422016.N().S(` = `)
//line template.qtpl:92
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:92
			qw422016.N().S(`(`)
//line template.qtpl:92
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:92
			qw422016.N().S(`)
`)
//line template.qtpl:93
		} else if p.Type().Pointer == 2 {
//line template.qtpl:93
			qw422016.N().S(`		if cefp != `)
//line template.qtpl:94
			streamgoTempNameOut(qw422016, p)
//line template.qtpl:94
			qw422016.N().S(`.p_`)
//line template.qtpl:94
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:94
			qw422016.N().S(` {
			*`)
//line template.qtpl:95
			qw422016.E().S(goParamName(p))
//line template.qtpl:95
			qw422016.N().S(` = `)
//line template.qtpl:95
			streamgoTempNameOut(qw422016, p)
//line template.qtpl:95
			qw422016.N().S(`.p_`)
//line template.qtpl:95
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:95
			qw422016.N().S(`
			BaseAddRef(*`)
//line template.qtpl:96
			qw422016.E().S(goParamName(p))
//line template.qtpl:96
			qw422016.N().S(`)
		}
`)
//line template.qtpl:98
		} else {
//line template.qtpl:99
			log.Panicf("E88: %s::%s::%s", p.CalleeName(), p.Name(), p.Type())

//line template.qtpl:100
		}
//line template.qtpl:101
	} else if p.Name() != "self" {
//line template.qtpl:102
		if p.IsRefCountedClass() {
//line template.qtpl:102
			qw422016.N().S(`		BaseRelease(`)
//line template.qtpl:103
			streamgoTempName(qw422016, p)
//line template.qtpl:103
			qw422016.N().S(`.p_`)
//line template.qtpl:103
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:103
			qw422016.N().S(`)
`)
//line template.qtpl:104
			*line += 1

//line template.qtpl:105
		}
//line template.qtpl:106
	}
//line template.qtpl:107
}

//line template.qtpl:107
func writepostProcess(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:107
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:107
	streampostProcess(qw422016, p, line)
//line template.qtpl:107
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:107
}

//line template.qtpl:107
func postProcess(p parser.Param, line *int) string {
//line template.qtpl:107
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:107
	writepostProcess(qb422016, p, line)
//line template.qtpl:107
	qs422016 := string(qb422016.B)
//line template.qtpl:107
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:107
	return qs422016
//line template.qtpl:107
}

//line template.qtpl:109
func StreamMethodComments(qw422016 *qt422016.Writer, m *parser.MethodDecl, line *int) {
//line template.qtpl:110
	for _, c := range m.Comment {
//line template.qtpl:111
		qw422016.E().S(c)
//line template.qtpl:111
		*line++

//line template.qtpl:111
		qw422016.N().S(`
`)
//line template.qtpl:112
	}
//line template.qtpl:113
}

//line template.qtpl:113
func WriteMethodComments(qq422016 qtio422016.Writer, m *parser.MethodDecl, line *int) {
//line template.qtpl:113
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:113
	StreamMethodComments(qw422016, m, line)
//line template.qtpl:113
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:113
}

//line template.qtpl:113
func MethodComments(m *parser.MethodDecl, line *int) string {
//line template.qtpl:113
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:113
	WriteMethodComments(qb422016, m, line)
//line template.qtpl:113
	qs422016 := string(qb422016.B)
//line template.qtpl:113
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:113
	return qs422016
//line template.qtpl:113
}

//line template.qtpl:115
func streamgoRecieveValue(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:116
	first := true

//line template.qtpl:117
	if m.HasReturnValue() {
//line template.qtpl:117
		qw422016.N().S(`goRet`)
//line template.qtpl:117
		first = false

//line template.qtpl:117
	}
//line template.qtpl:118
	for _, p := range m.Params() {
//line template.qtpl:119
		if p.IsOutParam() || p.IsInOutParam() {
//line template.qtpl:120
			if !first {
//line template.qtpl:120
				qw422016.N().S(`, `)
//line template.qtpl:120
			}
//line template.qtpl:121
			qw422016.E().S(goTempNameOut(p))
//line template.qtpl:121
			first = false

//line template.qtpl:122
		}
//line template.qtpl:123
	}
//line template.qtpl:124
	if m.HasReturnValue() || m.HasOutParam() {
//line template.qtpl:124
		qw422016.N().S(`:= `)
//line template.qtpl:124
	}
//line template.qtpl:125
}

//line template.qtpl:125
func writegoRecieveValue(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:125
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:125
	streamgoRecieveValue(qw422016, m)
//line template.qtpl:125
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:125
}

//line template.qtpl:125
func goRecieveValue(m *parser.MethodDecl) string {
//line template.qtpl:125
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:125
	writegoRecieveValue(qb422016, m)
//line template.qtpl:125
	qs422016 := string(qb422016.B)
//line template.qtpl:125
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:125
	return qs422016
//line template.qtpl:125
}

//line template.qtpl:127
func StreamGoCallback(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl, st *parser.CefClassDecl) {
//line template.qtpl:127
	qw422016.N().S(`
`)
//line template.qtpl:129
	var retCtype string
	retCtype = m.ReturnType().GoCType()
	baseName := st.BaseName()

//line template.qtpl:133
	StreamMethodComments(qw422016, m, &line)
//line template.qtpl:133
	qw422016.N().S(`//export cefingo_`)
//line template.qtpl:134
	qw422016.E().S(baseName)
//line template.qtpl:134
	qw422016.N().S(`_`)
//line template.qtpl:134
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:134
	qw422016.N().S(`
func cefingo_`)
//line template.qtpl:135
	qw422016.E().S(baseName)
//line template.qtpl:135
	qw422016.N().S(`_`)
//line template.qtpl:135
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:135
	qw422016.N().S(`(
`)
//line template.qtpl:136
	for _, p := range m.Params() {
//line template.qtpl:136
		qw422016.N().S(`	`)
//line template.qtpl:137
		qw422016.E().S(goParamName(p))
//line template.qtpl:137
		qw422016.N().S(` `)
//line template.qtpl:137
		qw422016.E().S(p.GoCType())
//line template.qtpl:137
		qw422016.N().S(`,`)
//line template.qtpl:137
		line += 1

//line template.qtpl:137
		qw422016.N().S(`
`)
//line template.qtpl:138
	}
//line template.qtpl:138
	qw422016.N().S(`) `)
//line template.qtpl:139
	if retCtype != "" {
//line template.qtpl:139
		qw422016.N().S(`(cRet `)
//line template.qtpl:139
		qw422016.E().S(retCtype)
//line template.qtpl:139
		qw422016.N().S(`)`)
//line template.qtpl:139
	}
//line template.qtpl:139
	qw422016.N().S(` {
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()

	Tracef(unsafe.Pointer(self), "T`)
//line template.qtpl:143
	qw422016.N().D(line + 5)
//line template.qtpl:143
	qw422016.N().S(`:")
	cefingoIfaceAccess.Lock()
`)
//line template.qtpl:145
	if "*C."+st.CefName() == m.Params()[0].GoCType() {
//line template.qtpl:145
		qw422016.N().S(`	f := `)
//line template.qtpl:146
		qw422016.E().S(baseName)
//line template.qtpl:146
		qw422016.N().S(`_handlers.`)
//line template.qtpl:146
		streammemberName(qw422016, m)
//line template.qtpl:146
		qw422016.N().S(`[self]
`)
//line template.qtpl:147
	} else {
//line template.qtpl:147
		qw422016.N().S(`	f := `)
//line template.qtpl:148
		qw422016.E().S(baseName)
//line template.qtpl:148
		qw422016.N().S(`_handlers.`)
//line template.qtpl:148
		streammemberName(qw422016, m)
//line template.qtpl:148
		qw422016.N().S(`[(*C.`)
//line template.qtpl:148
		qw422016.E().S(st.CefName())
//line template.qtpl:148
		qw422016.N().S(`)(unsafe.Pointer(self))]
`)
//line template.qtpl:149
	}
//line template.qtpl:149
	qw422016.N().S(`	cefingoIfaceAccess.Unlock()

	if f != nil {
`)
//line template.qtpl:153
	for _, p := range m.Params() {
//line template.qtpl:154
		if exp := convToGoTypeStmts(p, &line); exp != "" && !p.IsByteSliceLengthParam() {
//line template.qtpl:155
			qw422016.N().S(exp)
//line template.qtpl:156
		}
//line template.qtpl:157
	}
//line template.qtpl:157
	qw422016.N().S(`
		`)
//line template.qtpl:158
	streamgoRecieveValue(qw422016, m)
//line template.qtpl:158
	qw422016.N().S(`f.`)
//line template.qtpl:158
	qw422016.E().S(m.Funcname.TitleCase())
//line template.qtpl:158
	qw422016.E().S("(")
//line template.qtpl:159
	for _, p := range m.Params() {
//line template.qtpl:160
		if !(p.IsSliceLengthParam() || p.IsByteSliceLengthParam() || p.IsOutParam()) {
//line template.qtpl:160
			streamgoTempName(qw422016, p)
//line template.qtpl:160
			qw422016.N().S(`,`)
//line template.qtpl:160
		}
//line template.qtpl:161
	}
//line template.qtpl:161
	qw422016.N().S(`)
`)
//line template.qtpl:162
	for _, p := range m.Params() {
//line template.qtpl:163
		if exp := postProcess(p, &line); exp != "" {
//line template.qtpl:164
			qw422016.N().S(exp)
//line template.qtpl:165
		}
//line template.qtpl:166
	}
//line template.qtpl:166
	qw422016.N().S(`
`)
//line template.qtpl:167
	if m.IsBoolValueMethod() {
//line template.qtpl:167
		line += 1

//line template.qtpl:167
		qw422016.N().S(`		if goRet {cRet = 1}
`)
//line template.qtpl:169
	} else if m.ReturnType().IsRefCountedClass() {
//line template.qtpl:169
		line += 1

//line template.qtpl:169
		qw422016.N().S(`		cRet = (`)
//line template.qtpl:170
		qw422016.E().S(retCtype)
//line template.qtpl:170
		qw422016.N().S(`)(goRet.p_`)
//line template.qtpl:170
		qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:170
		qw422016.N().S(`)
		BaseAddRef(cRet)
`)
//line template.qtpl:172
	} else if retCtype != "" {
//line template.qtpl:172
		line += 1

//line template.qtpl:172
		qw422016.N().S(`		cRet = (`)
//line template.qtpl:173
		qw422016.E().S(retCtype)
//line template.qtpl:173
		qw422016.N().S(`)(goRet)
`)
//line template.qtpl:174
	}
//line template.qtpl:174
	qw422016.N().S(`	} else {
		Logf("T`)
//line template.qtpl:176
	qw422016.N().D(line + 15)
//line template.qtpl:176
	qw422016.N().S(`: `)
//line template.qtpl:176
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:176
	qw422016.N().S(`: Noo!")
	}
	`)
//line template.qtpl:178
	if retCtype != "" {
//line template.qtpl:178
		qw422016.N().S(`return cRet`)
//line template.qtpl:178
	}
//line template.qtpl:178
	qw422016.N().S(`
}
`)
//line template.qtpl:180
}

//line template.qtpl:180
func WriteGoCallback(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl, st *parser.CefClassDecl) {
//line template.qtpl:180
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:180
	StreamGoCallback(qw422016, line, m, st)
//line template.qtpl:180
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:180
}

//line template.qtpl:180
func GoCallback(line int, m *parser.MethodDecl, st *parser.CefClassDecl) string {
//line template.qtpl:180
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:180
	WriteGoCallback(qb422016, line, m, st)
//line template.qtpl:180
	qs422016 := string(qb422016.B)
//line template.qtpl:180
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:180
	return qs422016
//line template.qtpl:180
}

//line template.qtpl:182
func StreamGoBindFunc(qw422016 *qt422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:182
	qw422016.N().S(`
`)
//line template.qtpl:184
	goName := st.Common().GoName()
	baseName := st.Common().BaseName()
	self := baseName

//line template.qtpl:186
	qw422016.N().S(`func (`)
//line template.qtpl:187
	qw422016.E().S(self)
//line template.qtpl:187
	qw422016.N().S(` *`)
//line template.qtpl:187
	qw422016.E().S(goName)
//line template.qtpl:187
	qw422016.N().S(`) Bind(a interface{}) *`)
//line template.qtpl:187
	qw422016.E().S(goName)
//line template.qtpl:187
	qw422016.N().S(` {
	cefingoIfaceAccess.Lock()
	defer cefingoIfaceAccess.Unlock()
`)
//line template.qtpl:190
	funcnum := 0

//line template.qtpl:191
	for c := st; c != nil; c = c.GetBase() {
//line template.qtpl:192
		for _, m := range c.Methods {
//line template.qtpl:193
			if !m.IsGetFunc() {
//line template.qtpl:193
				qw422016.N().S(`
`)
//line template.qtpl:194
				if funcnum == 0 {
//line template.qtpl:194
					qw422016.N().S(`	cp := `)
//line template.qtpl:195
					qw422016.E().S(self)
//line template.qtpl:195
					qw422016.N().S(`.p_`)
//line template.qtpl:195
					qw422016.E().S(baseName)
//line template.qtpl:195
					qw422016.N().S(`

`)
//line template.qtpl:197
				}
//line template.qtpl:198
				funcnum += 1

//line template.qtpl:198
				qw422016.N().S(`	if h, ok := a.(`)
//line template.qtpl:199
				qw422016.E().S(m.IfName())
//line template.qtpl:199
				qw422016.N().S(`); ok {
		`)
//line template.qtpl:200
				qw422016.E().S(baseName)
//line template.qtpl:200
				qw422016.N().S(`_handlers.`)
//line template.qtpl:200
				streammemberName(qw422016, m)
//line template.qtpl:200
				qw422016.N().S(`[cp] = h
	}
`)
//line template.qtpl:202
			}
//line template.qtpl:203
		}
//line template.qtpl:204
	}
//line template.qtpl:204
	qw422016.N().S(`
	if accessor, ok := a.(`)
//line template.qtpl:205
	qw422016.E().S(goName)
//line template.qtpl:205
	qw422016.N().S(`Accessor); ok {
		accessor.Set`)
//line template.qtpl:206
	qw422016.E().S(goName)
//line template.qtpl:206
	qw422016.N().S(`(`)
//line template.qtpl:206
	qw422016.E().S(self)
//line template.qtpl:206
	qw422016.N().S(`)
		Logf("T`)
//line template.qtpl:207
	qw422016.N().D((line + funcnum*4) + 22)
//line template.qtpl:207
	qw422016.N().S(`:")
	}

	return `)
//line template.qtpl:210
	qw422016.E().S(self)
//line template.qtpl:210
	qw422016.N().S(`
}
`)
//line template.qtpl:212
}

//line template.qtpl:212
func WriteGoBindFunc(qq422016 qtio422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:212
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:212
	StreamGoBindFunc(qw422016, line, st)
//line template.qtpl:212
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:212
}

//line template.qtpl:212
func GoBindFunc(line int, st *parser.CefClassDecl) string {
//line template.qtpl:212
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:212
	WriteGoBindFunc(qb422016, line, st)
//line template.qtpl:212
	qs422016 := string(qb422016.B)
//line template.qtpl:212
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:212
	return qs422016
//line template.qtpl:212
}

//line template.qtpl:214
func StreamGoGetFunc(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:214
	qw422016.N().S(`
//export cefingo_`)
//line template.qtpl:215
	qw422016.E().S(baseName)
//line template.qtpl:215
	qw422016.N().S(`_`)
//line template.qtpl:215
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:215
	qw422016.N().S(`
func cefingo_`)
//line template.qtpl:216
	qw422016.E().S(baseName)
//line template.qtpl:216
	qw422016.N().S(`_`)
//line template.qtpl:216
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:216
	qw422016.N().S(`(self *C.`)
//line template.qtpl:216
	qw422016.E().S(cName)
//line template.qtpl:216
	qw422016.N().S(`) (ch `)
//line template.qtpl:216
	qw422016.E().S(m.ReturnType().GoCType())
//line template.qtpl:216
	qw422016.N().S(`) {
	cefingoIfaceAccess.Lock()
	defer cefingoIfaceAccess.Unlock()

	handler := `)
//line template.qtpl:220
	qw422016.E().S(baseName)
//line template.qtpl:220
	qw422016.N().S(`_handlers.`)
//line template.qtpl:220
	qw422016.E().S(memberName(m))
//line template.qtpl:220
	qw422016.N().S(`[self]
	if handler == nil {
		Logf("T`)
//line template.qtpl:222
	qw422016.N().D(line + 9)
//line template.qtpl:222
	qw422016.N().S(`: `)
//line template.qtpl:222
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:222
	qw422016.N().S(`")
	} else {
		BaseAddRef(handler.p_`)
//line template.qtpl:224
	qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:224
	qw422016.N().S(`)
		ch = handler.p_`)
//line template.qtpl:225
	qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:225
	qw422016.N().S(`
	}
	return ch
}
`)
//line template.qtpl:229
}

//line template.qtpl:229
func WriteGoGetFunc(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:229
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:229
	StreamGoGetFunc(qw422016, line, m, goName, baseName, cName)
//line template.qtpl:229
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:229
}

//line template.qtpl:229
func GoGetFunc(line int, m *parser.MethodDecl, goName, baseName, cName string) string {
//line template.qtpl:229
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:229
	WriteGoGetFunc(qb422016, line, m, goName, baseName, cName)
//line template.qtpl:229
	qs422016 := string(qb422016.B)
//line template.qtpl:229
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:229
	return qs422016
//line template.qtpl:229
}

//line template.qtpl:231
func StreamAssocGetFunc(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:231
	qw422016.N().S(`
func (`)
//line template.qtpl:232
	qw422016.E().S(baseName)
//line template.qtpl:232
	qw422016.N().S(` *`)
//line template.qtpl:232
	qw422016.E().S(goName)
//line template.qtpl:232
	qw422016.N().S(`) Assoc`)
//line template.qtpl:232
	qw422016.E().S(m.ReturnType().TitleCase())
//line template.qtpl:232
	qw422016.N().S(`(handler `)
//line template.qtpl:232
	qw422016.E().S(m.ReturnType().GoType())
//line template.qtpl:232
	qw422016.N().S(`) {
	cp := `)
//line template.qtpl:233
	qw422016.E().S(baseName)
//line template.qtpl:233
	qw422016.N().S(`.p_`)
//line template.qtpl:233
	qw422016.E().S(baseName)
//line template.qtpl:233
	qw422016.N().S(`
	cefingoIfaceAccess.Lock()
	defer cefingoIfaceAccess.Unlock()

	`)
//line template.qtpl:237
	qw422016.E().S(baseName)
//line template.qtpl:237
	qw422016.N().S(`_handlers.`)
//line template.qtpl:237
	streammemberName(qw422016, m)
//line template.qtpl:237
	qw422016.N().S(`[cp] = handler
}
`)
//line template.qtpl:239
}

//line template.qtpl:239
func WriteAssocGetFunc(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl, goName, baseName, cName string) {
//line template.qtpl:239
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:239
	StreamAssocGetFunc(qw422016, line, m, goName, baseName, cName)
//line template.qtpl:239
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:239
}

//line template.qtpl:239
func AssocGetFunc(line int, m *parser.MethodDecl, goName, baseName, cName string) string {
//line template.qtpl:239
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:239
	WriteAssocGetFunc(qb422016, line, m, goName, baseName, cName)
//line template.qtpl:239
	qs422016 := string(qb422016.B)
//line template.qtpl:239
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:239
	return qs422016
//line template.qtpl:239
}

//line template.qtpl:241
func StreamGoHead(qw422016 *qt422016.Writer, imports []string, defIfMutex, winOnly bool) {
//line template.qtpl:241
	qw422016.N().S(`
// Code generated by "gen-cefingo.go" DO NOT EDIT.
`)
//line template.qtpl:243
	if winOnly {
//line template.qtpl:243
		qw422016.N().S(`// +build windows
`)
//line template.qtpl:245
	}
//line template.qtpl:245
	qw422016.N().S(`package capi

`)
//line template.qtpl:248
	if len(imports) > 0 {
//line template.qtpl:248
		qw422016.N().S(`import (
`)
//line template.qtpl:250
		for _, p := range imports {
//line template.qtpl:250
			qw422016.N().S(`	"`)
//line template.qtpl:251
			qw422016.E().S(p)
//line template.qtpl:251
			qw422016.N().S(`"
`)
//line template.qtpl:252
		}
//line template.qtpl:252
		qw422016.N().S(`)
`)
//line template.qtpl:254
	}
//line template.qtpl:254
	qw422016.N().S(`// #include "cefingo.h"
import "C"
`)
//line template.qtpl:257
	if defIfMutex {
//line template.qtpl:257
		qw422016.N().S(`var cefingoIfaceAccess sync.Mutex
`)
//line template.qtpl:258
	}
//line template.qtpl:259
}

//line template.qtpl:259
func WriteGoHead(qq422016 qtio422016.Writer, imports []string, defIfMutex, winOnly bool) {
//line template.qtpl:259
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:259
	StreamGoHead(qw422016, imports, defIfMutex, winOnly)
//line template.qtpl:259
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:259
}

//line template.qtpl:259
func GoHead(imports []string, defIfMutex, winOnly bool) string {
//line template.qtpl:259
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:259
	WriteGoHead(qb422016, imports, defIfMutex, winOnly)
//line template.qtpl:259
	qs422016 := string(qb422016.B)
//line template.qtpl:259
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:259
	return qs422016
//line template.qtpl:259
}

//line template.qtpl:261
func StreamGoIface(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:261
	qw422016.N().S(`
`)
//line template.qtpl:262
	StreamMethodComments(qw422016, m, &line)
//line template.qtpl:262
	qw422016.N().S(`type `)
//line template.qtpl:263
	qw422016.E().S(m.IfName())
//line template.qtpl:263
	qw422016.N().S(` interface {
	`)
//line template.qtpl:264
	qw422016.E().S(m.Funcname.TitleCase())
//line template.qtpl:264
	qw422016.N().S(` (
`)
//line template.qtpl:265
	for _, p := range m.Params() {
//line template.qtpl:266
		if !(p.IsSliceLengthParam() || p.IsByteSliceLengthParam() || p.IsOutParam()) {
//line template.qtpl:266
			qw422016.N().S(`		`)
//line template.qtpl:267
			qw422016.E().S(goParamName(p))
//line template.qtpl:267
			qw422016.N().S(` `)
//line template.qtpl:267
			qw422016.E().S(p.GoTypeIn())
//line template.qtpl:267
			qw422016.N().S(`,
`)
//line template.qtpl:268
		}
//line template.qtpl:269
	}
//line template.qtpl:269
	qw422016.N().S(`	) `)
//line template.qtpl:270
	qw422016.E().S(retTypes(m))
//line template.qtpl:270
	qw422016.N().S(`
}
`)
//line template.qtpl:272
}

//line template.qtpl:272
func WriteGoIface(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:272
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:272
	StreamGoIface(qw422016, line, m)
//line template.qtpl:272
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:272
}

//line template.qtpl:272
func GoIface(line int, m *parser.MethodDecl) string {
//line template.qtpl:272
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:272
	WriteGoIface(qb422016, line, m)
//line template.qtpl:272
	qs422016 := string(qb422016.B)
//line template.qtpl:272
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:272
	return qs422016
//line template.qtpl:272
}

//line template.qtpl:274
func streammemberName(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:275
	if m.IsGetFunc() {
//line template.qtpl:276
		qw422016.E().S(m.ReturnType().BaseName())
//line template.qtpl:277
	} else {
//line template.qtpl:278
		qw422016.E().S(m.Funcname.Name())
//line template.qtpl:278
		qw422016.N().S(`_handler`)
//line template.qtpl:278
		qw422016.E().S("")
//line template.qtpl:279
	}
//line template.qtpl:280
}

//line template.qtpl:280
func writememberName(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:280
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:280
	streammemberName(qw422016, m)
//line template.qtpl:280
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:280
}

//line template.qtpl:280
func memberName(m *parser.MethodDecl) string {
//line template.qtpl:280
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:280
	writememberName(qb422016, m)
//line template.qtpl:280
	qs422016 := string(qb422016.B)
//line template.qtpl:280
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:280
	return qs422016
//line template.qtpl:280
}

//line template.qtpl:282
func streammemberGoType(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:283
	if m.IsGetFunc() {
//line template.qtpl:284
		qw422016.E().S(m.ReturnType().GoType())
//line template.qtpl:285
	} else {
//line template.qtpl:286
		qw422016.E().S(m.IfName())
//line template.qtpl:287
	}
//line template.qtpl:288
}

//line template.qtpl:288
func writememberGoType(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:288
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:288
	streammemberGoType(qw422016, m)
//line template.qtpl:288
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:288
}

//line template.qtpl:288
func memberGoType(m *parser.MethodDecl) string {
//line template.qtpl:288
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:288
	writememberGoType(qb422016, m)
//line template.qtpl:288
	qs422016 := string(qb422016.B)
//line template.qtpl:288
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:288
	return qs422016
//line template.qtpl:288
}

//line template.qtpl:290
func StreamIfaceStruct(qw422016 *qt422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:290
	qw422016.N().S(`
var `)
//line template.qtpl:291
	qw422016.E().S(st.BaseName())
//line template.qtpl:291
	qw422016.N().S(`_handlers = struct {
`)
//line template.qtpl:292
	for c := st; c != nil; c = c.GetBase() {
//line template.qtpl:293
		for _, m := range c.Methods {
//line template.qtpl:293
			qw422016.N().S(`	`)
//line template.qtpl:294
			streammemberName(qw422016, m)
//line template.qtpl:294
			qw422016.N().S(` map[*C.`)
//line template.qtpl:294
			qw422016.E().S(st.CefName())
//line template.qtpl:294
			qw422016.N().S(`]`)
//line template.qtpl:294
			streammemberGoType(qw422016, m)
//line template.qtpl:294
			qw422016.N().S(`
`)
//line template.qtpl:295
		}
//line template.qtpl:296
	}
//line template.qtpl:296
	qw422016.N().S(`}{
`)
//line template.qtpl:298
	for c := st; c != nil; c = c.GetBase() {
//line template.qtpl:299
		for _, m := range c.Methods {
//line template.qtpl:299
			qw422016.N().S(`	map[*C.`)
//line template.qtpl:300
			qw422016.E().S(st.CefName())
//line template.qtpl:300
			qw422016.N().S(`]`)
//line template.qtpl:300
			streammemberGoType(qw422016, m)
//line template.qtpl:300
			qw422016.N().S(`{},
`)
//line template.qtpl:301
		}
//line template.qtpl:302
	}
//line template.qtpl:302
	qw422016.N().S(`}
`)
//line template.qtpl:304
}

//line template.qtpl:304
func WriteIfaceStruct(qq422016 qtio422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:304
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:304
	StreamIfaceStruct(qw422016, line, st)
//line template.qtpl:304
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:304
}

//line template.qtpl:304
func IfaceStruct(line int, st *parser.CefClassDecl) string {
//line template.qtpl:304
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:304
	WriteIfaceStruct(qb422016, line, st)
//line template.qtpl:304
	qs422016 := string(qb422016.B)
//line template.qtpl:304
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:304
	return qs422016
//line template.qtpl:304
}

//line template.qtpl:306
func StreamGoAllocFunc(qw422016 *qt422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:306
	qw422016.N().S(`
// Alloc`)
//line template.qtpl:307
	qw422016.E().S(st.GoName())
//line template.qtpl:307
	qw422016.N().S(` allocates `)
//line template.qtpl:307
	qw422016.E().S(st.GoName())
//line template.qtpl:307
	qw422016.N().S(` and construct it
func Alloc`)
//line template.qtpl:308
	qw422016.E().S(st.GoName())
//line template.qtpl:308
	qw422016.N().S(`() *`)
//line template.qtpl:308
	qw422016.E().S(st.GoName())
//line template.qtpl:308
	qw422016.N().S(` {
	up := c_calloc(1, C.sizeof_cefingo_`)
//line template.qtpl:309
	qw422016.E().S(st.BaseName())
//line template.qtpl:309
	qw422016.N().S(`_wrapper_t, "T`)
//line template.qtpl:309
	qw422016.N().D(line + 4)
//line template.qtpl:309
	qw422016.N().S(`:")
	cefp := C.cefingo_construct_`)
//line template.qtpl:310
	qw422016.E().S(st.BaseName())
//line template.qtpl:310
	qw422016.N().S(`((*C.cefingo_`)
//line template.qtpl:310
	qw422016.E().S(st.BaseName())
//line template.qtpl:310
	qw422016.N().S(`_wrapper_t)(up))

	registerDeassocer(up, DeassocFunc(func() {
		// Do not have reference to `)
//line template.qtpl:313
	qw422016.E().S(st.CefName())
//line template.qtpl:313
	qw422016.N().S(` itself in DeassocFunc,
		// or `)
//line template.qtpl:314
	qw422016.E().S(st.CefName())
//line template.qtpl:314
	qw422016.N().S(` is never GCed.
		Tracef(up, "T`)
//line template.qtpl:315
	qw422016.N().D(line + 10)
//line template.qtpl:315
	qw422016.N().S(`:")

		cefingoIfaceAccess.Lock()
		defer cefingoIfaceAccess.Unlock()
`)
//line template.qtpl:319
	for c := st; c != nil; c = c.GetBase() {
//line template.qtpl:320
		for _, m := range c.Methods {
//line template.qtpl:320
			qw422016.N().S(`		delete(`)
//line template.qtpl:321
			qw422016.E().S(st.BaseName())
//line template.qtpl:321
			qw422016.N().S(`_handlers.`)
//line template.qtpl:321
			streammemberName(qw422016, m)
//line template.qtpl:321
			qw422016.N().S(`, cefp)
`)
//line template.qtpl:322
		}
//line template.qtpl:323
	}
//line template.qtpl:323
	qw422016.N().S(`	}))

	return new`)
//line template.qtpl:326
	qw422016.E().S(st.GoName())
//line template.qtpl:326
	qw422016.N().S(`(cefp)
}
`)
//line template.qtpl:328
}

//line template.qtpl:328
func WriteGoAllocFunc(qq422016 qtio422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:328
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:328
	StreamGoAllocFunc(qw422016, line, st)
//line template.qtpl:328
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:328
}

//line template.qtpl:328
func GoAllocFunc(line int, st *parser.CefClassDecl) string {
//line template.qtpl:328
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:328
	WriteGoAllocFunc(qb422016, line, st)
//line template.qtpl:328
	qs422016 := string(qb422016.B)
//line template.qtpl:328
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:328
	return qs422016
//line template.qtpl:328
}

//line template.qtpl:330
func streammethodCTypeName(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:331
	callee := strings.Replace(m.CalleeName(), "::", "_", 1)

//line template.qtpl:331
	qw422016.N().S(`T_`)
//line template.qtpl:332
	qw422016.E().S(strings.ToUpper(callee))
//line template.qtpl:333
}

//line template.qtpl:333
func writemethodCTypeName(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:333
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:333
	streammethodCTypeName(qw422016, m)
//line template.qtpl:333
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:333
}

//line template.qtpl:333
func methodCTypeName(m *parser.MethodDecl) string {
//line template.qtpl:333
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:333
	writemethodCTypeName(qb422016, m)
//line template.qtpl:333
	qs422016 := string(qb422016.B)
//line template.qtpl:333
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:333
	return qs422016
//line template.qtpl:333
}

//line template.qtpl:335
func streamconstructorName(qw422016 *qt422016.Writer, st *parser.CefClassDecl) {
//line template.qtpl:336
	qw422016.E().S(st.CefName() + " *cefingo_construct_" + st.BaseName() + "(cefingo_" + st.BaseName() + "_wrapper_t* " + st.BaseName() + ")")
//line template.qtpl:337
}

//line template.qtpl:337
func writeconstructorName(qq422016 qtio422016.Writer, st *parser.CefClassDecl) {
//line template.qtpl:337
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:337
	streamconstructorName(qw422016, st)
//line template.qtpl:337
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:337
}

//line template.qtpl:337
func constructorName(st *parser.CefClassDecl) string {
//line template.qtpl:337
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:337
	writeconstructorName(qb422016, st)
//line template.qtpl:337
	qs422016 := string(qb422016.B)
//line template.qtpl:337
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:337
	return qs422016
//line template.qtpl:337
}

//line template.qtpl:339
func StreamCConstruct(qw422016 *qt422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:339
	qw422016.N().S(`
`)
//line template.qtpl:340
	for _, m := range st.Methods {
//line template.qtpl:341
		if m.HasConstParams() {
//line template.qtpl:341
			qw422016.N().S(`typedef `)
//line template.qtpl:342
			qw422016.E().S(m.ReturnType().CType())
//line template.qtpl:342
			qw422016.N().S(` (*`)
//line template.qtpl:343
			qw422016.E().S(methodCTypeName(m))
//line template.qtpl:343
			qw422016.N().S(`)(
`)
//line template.qtpl:344
			for i, p := range m.Params() {
//line template.qtpl:345
				if i > 0 {
//line template.qtpl:345
					qw422016.N().S(`, 
`)
//line template.qtpl:346
				}
//line template.qtpl:346
				qw422016.N().S(`	`)
//line template.qtpl:346
				qw422016.E().S(p.CType())
//line template.qtpl:347
			}
//line template.qtpl:347
			qw422016.N().S(`
);
`)
//line template.qtpl:349
		}
//line template.qtpl:350
	}
//line template.qtpl:350
	qw422016.N().S(`
`)
//line template.qtpl:352
	qw422016.E().S(constructorName(st))
//line template.qtpl:352
	qw422016.N().S(`
{
	initialize_cefingo_base_ref_counted(
		offsetof(__typeof__(*`)
//line template.qtpl:355
	qw422016.E().S(st.BaseName())
//line template.qtpl:355
	qw422016.N().S(`), counter),
		(cef_base_ref_counted_t*) `)
//line template.qtpl:356
	qw422016.E().S(st.BaseName())
//line template.qtpl:356
	qw422016.N().S(`);
	
	// callbacks
`)
//line template.qtpl:359
	base := ""

//line template.qtpl:360
	for c := st; c != nil; c = c.GetBase() {
//line template.qtpl:361
		for _, m := range c.Methods {
//line template.qtpl:361
			qw422016.N().S(`	`)
//line template.qtpl:362
			qw422016.E().S(st.BaseName())
//line template.qtpl:362
			qw422016.N().S(`->body`)
//line template.qtpl:362
			qw422016.E().S(base)
//line template.qtpl:362
			qw422016.N().S(`.`)
//line template.qtpl:362
			qw422016.E().S(m.Funcname.Name())
//line template.qtpl:362
			qw422016.N().S(` = `)
//line template.qtpl:362
			if m.HasConstParams() {
//line template.qtpl:362
				qw422016.N().S(`(`)
//line template.qtpl:362
				qw422016.E().S(methodCTypeName(m))
//line template.qtpl:362
				qw422016.N().S(`)`)
//line template.qtpl:362
			}
//line template.qtpl:362
			qw422016.N().S(`
		cefingo_`)
//line template.qtpl:363
			qw422016.E().S(st.BaseName())
//line template.qtpl:363
			qw422016.N().S(`_`)
//line template.qtpl:363
			qw422016.E().S(m.Funcname.Name())
//line template.qtpl:363
			qw422016.N().S(`;
`)
//line template.qtpl:364
		}
//line template.qtpl:365
		base = base + ".base"

//line template.qtpl:366
	}
//line template.qtpl:366
	qw422016.N().S(`
	return (`)
//line template.qtpl:368
	qw422016.E().S(st.CefName())
//line template.qtpl:368
	qw422016.N().S(`*)`)
//line template.qtpl:368
	qw422016.E().S(st.BaseName())
//line template.qtpl:368
	qw422016.N().S(`;
}
`)
//line template.qtpl:370
}

//line template.qtpl:370
func WriteCConstruct(qq422016 qtio422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:370
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:370
	StreamCConstruct(qw422016, line, st)
//line template.qtpl:370
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:370
}

//line template.qtpl:370
func CConstruct(line int, st *parser.CefClassDecl) string {
//line template.qtpl:370
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:370
	WriteCConstruct(qb422016, line, st)
//line template.qtpl:370
	qs422016 := string(qb422016.B)
//line template.qtpl:370
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:370
	return qs422016
//line template.qtpl:370
}

//line template.qtpl:372
func StreamHCallback(qw422016 *qt422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:372
	qw422016.N().S(`
CEFINGO_REF_COUNTER_WRAPPER(cef_`)
//line template.qtpl:373
	qw422016.E().S(st.BaseName())
//line template.qtpl:373
	qw422016.N().S(`_t, cefingo_`)
//line template.qtpl:373
	qw422016.E().S(st.BaseName())
//line template.qtpl:373
	qw422016.N().S(`_wrapper_t);
extern `)
//line template.qtpl:374
	qw422016.E().S(constructorName(st))
//line template.qtpl:374
	qw422016.N().S(`;
`)
//line template.qtpl:375
}

//line template.qtpl:375
func WriteHCallback(qq422016 qtio422016.Writer, line int, st *parser.CefClassDecl) {
//line template.qtpl:375
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:375
	StreamHCallback(qw422016, line, st)
//line template.qtpl:375
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:375
}

//line template.qtpl:375
func HCallback(line int, st *parser.CefClassDecl) string {
//line template.qtpl:375
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:375
	WriteHCallback(qb422016, line, st)
//line template.qtpl:375
	qs422016 := string(qb422016.B)
//line template.qtpl:375
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:375
	return qs422016
//line template.qtpl:375
}

//line template.qtpl:377
func streampreConvToC(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:378
	if p.IsOutParam() {
//line template.qtpl:379
		if ok, argLen := p.IsByteSliceParam(); ok {
//line template.qtpl:379
			qw422016.N().S(`	`)
//line template.qtpl:380
			qw422016.E().S(argLen)
//line template.qtpl:380
			qw422016.N().S(` := len(`)
//line template.qtpl:380
			qw422016.E().S(goParamName(p))
//line template.qtpl:380
			qw422016.N().S(`)
	`)
//line template.qtpl:381
			qw422016.E().S(cTempName(p))
//line template.qtpl:381
			qw422016.N().S(` := c_calloc(1, C.size_t(`)
//line template.qtpl:381
			qw422016.E().S(argLen)
//line template.qtpl:381
			qw422016.N().S(`), "T`)
//line template.qtpl:381
			qw422016.N().D(*line)
//line template.qtpl:381
			qw422016.N().S(`:`)
//line template.qtpl:381
			qw422016.E().S(p.CalleeName() + "::" + p.Name())
//line template.qtpl:381
			qw422016.N().S(`")
`)
//line template.qtpl:382
		} else if isSlice, argLen := p.IsSliceParam(); isSlice {
//line template.qtpl:382
			qw422016.N().S(`	var _`)
//line template.qtpl:383
			qw422016.E().S(argLen)
//line template.qtpl:383
			qw422016.N().S(` C.size_t
	`)
//line template.qtpl:384
			qw422016.E().S(argLen)
//line template.qtpl:384
			qw422016.N().S(` := &_`)
//line template.qtpl:384
			qw422016.E().S(argLen)
//line template.qtpl:384
			qw422016.N().S(`
	var `)
//line template.qtpl:385
			qw422016.E().S(cTempName(p))
//line template.qtpl:385
			qw422016.N().S(` `)
//line template.qtpl:385
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:385
			qw422016.N().S(`
`)
//line template.qtpl:386
		} else if p.Type().Ty == parser.TyStringT {
//line template.qtpl:386
			qw422016.N().S(`	`)
//line template.qtpl:387
			qw422016.E().S(cTempName(p))
//line template.qtpl:387
			qw422016.N().S(` := create_cef_string("")
	defer clear_cef_string(`)
//line template.qtpl:388
			qw422016.E().S(cTempName(p))
//line template.qtpl:388
			qw422016.N().S(`)
`)
//line template.qtpl:389
		} else {
//line template.qtpl:389
			qw422016.N().S(`	var `)
//line template.qtpl:390
			qw422016.E().S(cTempName(p))
//line template.qtpl:390
			qw422016.N().S(` `)
//line template.qtpl:390
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:390
			qw422016.N().S(`
`)
//line template.qtpl:391
		}
//line template.qtpl:392
	} else if ok, argLen := p.IsByteSliceParam(); ok && !p.IsInOutParam() {
//line template.qtpl:392
		qw422016.N().S(`	`)
//line template.qtpl:393
		qw422016.E().S(argLen)
//line template.qtpl:393
		qw422016.N().S(` := len(`)
//line template.qtpl:393
		qw422016.E().S(goParamName(p))
//line template.qtpl:393
		qw422016.N().S(`)
	`)
//line template.qtpl:394
		qw422016.E().S(cTempName(p))
//line template.qtpl:394
		qw422016.N().S(` := C.CBytes(`)
//line template.qtpl:394
		qw422016.E().S(goParamName(p))
//line template.qtpl:394
		qw422016.N().S(`)
`)
//line template.qtpl:395
	} else if ok, argLen := p.IsSliceParam(); ok {
//line template.qtpl:395
		qw422016.N().S(`	`)
//line template.qtpl:396
		qw422016.E().S(argLen)
//line template.qtpl:396
		qw422016.N().S(` := len(`)
//line template.qtpl:396
		qw422016.E().S(goParamName(p))
//line template.qtpl:396
		qw422016.N().S(`)
	`)
//line template.qtpl:397
		qw422016.E().S(cTempName(p))
//line template.qtpl:397
		qw422016.N().S(` := c_calloc(C.size_t(`)
//line template.qtpl:397
		qw422016.E().S(argLen)
//line template.qtpl:397
		qw422016.N().S(`), (C.size_t)(unsafe.Sizeof(`)
//line template.qtpl:397
		streamgoParamName(qw422016, p)
//line template.qtpl:397
		qw422016.N().S(`[0])), "T`)
//line template.qtpl:397
		qw422016.N().D(*line)
//line template.qtpl:397
		qw422016.N().S(`:`)
//line template.qtpl:397
		qw422016.E().S(p.CalleeName() + "::" + p.Name())
//line template.qtpl:397
		qw422016.N().S(`")
	slice := (*[1 << 30]`)
//line template.qtpl:398
		qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:398
		qw422016.N().S(`)(`)
//line template.qtpl:398
		qw422016.E().S(cTempName(p))
//line template.qtpl:398
		qw422016.N().S(`)[:`)
//line template.qtpl:398
		qw422016.E().S(argLen)
//line template.qtpl:398
		qw422016.N().S(`:`)
//line template.qtpl:398
		qw422016.E().S(argLen)
//line template.qtpl:398
		qw422016.N().S(`]
	for i, v := range `)
//line template.qtpl:399
		qw422016.E().S(goParamName(p))
//line template.qtpl:399
		qw422016.N().S(` {
		cefp := v.p_`)
//line template.qtpl:400
		qw422016.E().S(p.Type().BaseName())
//line template.qtpl:400
		qw422016.N().S(`
		if cefp != nil {
			BaseAddRef(cefp)
		}
		slice[i] = cefp
	}
`)
//line template.qtpl:406
	} else if p.Type().IsRefCountedClass() {
//line template.qtpl:406
		qw422016.N().S(`	var `)
//line template.qtpl:407
		streamgoTempName(qw422016, p)
//line template.qtpl:407
		qw422016.N().S(` `)
//line template.qtpl:407
		qw422016.E().S(p.GoCType())
//line template.qtpl:407
		qw422016.N().S(` 
	if `)
//line template.qtpl:408
		streamgoParamName(qw422016, p)
//line template.qtpl:408
		qw422016.N().S(` != nil {
		`)
//line template.qtpl:409
		streamgoTempName(qw422016, p)
//line template.qtpl:409
		qw422016.N().S(` = `)
//line template.qtpl:409
		qw422016.E().S(goParamName(p))
//line template.qtpl:409
		qw422016.N().S(`.p_`)
//line template.qtpl:409
		qw422016.E().S(p.Type().BaseName())
//line template.qtpl:409
		qw422016.N().S(`
		BaseAddRef(`)
//line template.qtpl:410
		streamgoTempName(qw422016, p)
//line template.qtpl:410
		qw422016.N().S(`)
	}
`)
//line template.qtpl:412
	} else {
//line template.qtpl:413
		switch p.GoType() {
//line template.qtpl:414
		case "bool":
//line template.qtpl:415
			*line += 4

//line template.qtpl:415
			qw422016.N().S(`	var `)
//line template.qtpl:416
			qw422016.E().S(cTempName(p))
//line template.qtpl:416
			qw422016.N().S(` int
	if `)
//line template.qtpl:417
			qw422016.E().S(goParamName(p))
//line template.qtpl:417
			qw422016.N().S(` {
		`)
//line template.qtpl:418
			qw422016.E().S(cTempName(p))
//line template.qtpl:418
			qw422016.N().S(` = 1
	}
`)
//line template.qtpl:420
		case "string":
//line template.qtpl:421
			*line += 2

//line template.qtpl:421
			qw422016.N().S(`	`)
//line template.qtpl:422
			qw422016.E().S(cName(p))
//line template.qtpl:422
			qw422016.N().S(` := create_cef_string(`)
//line template.qtpl:422
			qw422016.E().S(goParamName(p))
//line template.qtpl:422
			qw422016.N().S(`)
	defer clear_cef_string(`)
//line template.qtpl:423
			qw422016.E().S(cName(p))
//line template.qtpl:423
			qw422016.N().S(`)
`)
//line template.qtpl:424
		case "time.Time":
//line template.qtpl:425
			*line += 1

//line template.qtpl:425
			qw422016.N().S(`	`)
//line template.qtpl:426
			qw422016.E().S(cName(p))
//line template.qtpl:426
			qw422016.N().S(` := `)
//line template.qtpl:426
			qw422016.E().S(goParamName(p))
//line template.qtpl:426
			qw422016.N().S(`.Unix()
`)
//line template.qtpl:427
		}
//line template.qtpl:428
	}
//line template.qtpl:429
}

//line template.qtpl:429
func writepreConvToC(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:429
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:429
	streampreConvToC(qw422016, p, line)
//line template.qtpl:429
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:429
}

//line template.qtpl:429
func preConvToC(p parser.Param, line *int) string {
//line template.qtpl:429
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:429
	writepreConvToC(qb422016, p, line)
//line template.qtpl:429
	qs422016 := string(qb422016.B)
//line template.qtpl:429
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:429
	return qs422016
//line template.qtpl:429
}

//line template.qtpl:431
func streamcName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:432
	switch p.Type().GoType() {
//line template.qtpl:433
	case "string", "*time.Time", "time.Time":
//line template.qtpl:433
		qw422016.N().S(`c_`)
//line template.qtpl:434
	}
//line template.qtpl:434
	qw422016.E().S(goParamName(p))
//line template.qtpl:435
}

//line template.qtpl:435
func writecName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:435
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:435
	streamcName(qw422016, p)
//line template.qtpl:435
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:435
}

//line template.qtpl:435
func cName(p parser.Param) string {
//line template.qtpl:435
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:435
	writecName(qb422016, p)
//line template.qtpl:435
	qs422016 := string(qb422016.B)
//line template.qtpl:435
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:435
	return qs422016
//line template.qtpl:435
}

//line template.qtpl:437
func streamcTempName(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:437
	qw422016.N().S(`tmp`)
//line template.qtpl:438
	streamcName(qw422016, p)
//line template.qtpl:439
}

//line template.qtpl:439
func writecTempName(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:439
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:439
	streamcTempName(qw422016, p)
//line template.qtpl:439
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:439
}

//line template.qtpl:439
func cTempName(p parser.Param) string {
//line template.qtpl:439
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:439
	writecTempName(qb422016, p)
//line template.qtpl:439
	qs422016 := string(qb422016.B)
//line template.qtpl:439
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:439
	return qs422016
//line template.qtpl:439
}

//line template.qtpl:441
func streamconvToC(qw422016 *qt422016.Writer, p parser.Param) {
//line template.qtpl:442
	if p.IsOutParam() {
//line template.qtpl:443
		if ok, _ := p.IsByteSliceParam(); ok {
//line template.qtpl:444
			qw422016.N().S(cTempName(p))
//line template.qtpl:445
		} else if p.Type().Ty == parser.TyStringT {
//line template.qtpl:446
			qw422016.N().S(cTempName(p))
//line template.qtpl:447
		} else {
//line template.qtpl:448
			qw422016.N().S("&" + cTempName(p))
//line template.qtpl:449
		}
//line template.qtpl:450
	} else if p.IsRefCountedClass() {
//line template.qtpl:451
		if p.Name() == "self" {
//line template.qtpl:451
			qw422016.N().S(`self.p_`)
//line template.qtpl:451
			qw422016.E().S(p.Type().BaseName())
//line template.qtpl:452
		} else {
//line template.qtpl:452
			qw422016.E().S(goTempName(p))
//line template.qtpl:452
		}
//line template.qtpl:453
	} else if p.IsScopedClass() {
//line template.qtpl:454
		qw422016.E().S(cName(p))
//line template.qtpl:454
		qw422016.N().S(`.p_`)
//line template.qtpl:454
		qw422016.E().S(p.Type().BaseName())
//line template.qtpl:455
	} else if ok, _ := p.IsByteSliceParam(); ok && !p.IsInOutParam() {
//line template.qtpl:456
		qw422016.N().S(cTempName(p))
//line template.qtpl:457
	} else if ok, _ := p.IsSliceParam(); ok {
//line template.qtpl:457
		qw422016.N().S(`	(`)
//line template.qtpl:458
		qw422016.E().S(p.GoCType())
//line template.qtpl:458
		qw422016.N().S(`)(`)
//line template.qtpl:458
		streamcTempName(qw422016, p)
//line template.qtpl:458
		qw422016.E().S(")")
//line template.qtpl:459
	} else {
//line template.qtpl:460
		switch p.GoType() {
//line template.qtpl:461
		case "bool":
//line template.qtpl:462
			qw422016.E().S(p.GoCType())
//line template.qtpl:462
			qw422016.N().S(`(`)
//line template.qtpl:462
			qw422016.E().S(cTempName(p) + ")")
//line template.qtpl:463
		case "*time.Time":
//line template.qtpl:464
			qw422016.N().S("&" + cName(p))
//line template.qtpl:465
		case "time.Time":
//line template.qtpl:466
			qw422016.E().S("C.time_t(" + cName(p) + ")")
//line template.qtpl:467
		case "unsafe.Pointer":
//line template.qtpl:467
			log.Printf("T335: %s::%s\n", p.CalleeName(), p.Name())

//line template.qtpl:468
			qw422016.E().S(cName(p))
//line template.qtpl:469
		default:
//line template.qtpl:470
			qw422016.E().S("(" + p.GoCType() + ")(")
//line template.qtpl:470
			qw422016.E().S(cName(p))
//line template.qtpl:470
			qw422016.E().S(")")
//line template.qtpl:471
		}
//line template.qtpl:472
	}
//line template.qtpl:473
}

//line template.qtpl:473
func writeconvToC(qq422016 qtio422016.Writer, p parser.Param) {
//line template.qtpl:473
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:473
	streamconvToC(qw422016, p)
//line template.qtpl:473
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:473
}

//line template.qtpl:473
func convToC(p parser.Param) string {
//line template.qtpl:473
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:473
	writeconvToC(qb422016, p)
//line template.qtpl:473
	qs422016 := string(qb422016.B)
//line template.qtpl:473
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:473
	return qs422016
//line template.qtpl:473
}

//line template.qtpl:475
func streampostConvFromC(qw422016 *qt422016.Writer, p parser.Param, line *int) {
//line template.qtpl:476
	if p.IsOutParam() {
//line template.qtpl:477
		if isSlice, argLen := p.IsByteSliceParam(); isSlice {
//line template.qtpl:477
			qw422016.N().S(`	`)
//line template.qtpl:478
			qw422016.E().S(goParamName(p))
//line template.qtpl:478
			qw422016.N().S(` = C.GoBytes(`)
//line template.qtpl:478
			qw422016.E().S(cTempName(p))
//line template.qtpl:478
			qw422016.N().S(`, C.int(`)
//line template.qtpl:478
			qw422016.E().S(argLen)
//line template.qtpl:478
			qw422016.N().S(`))
	C.free(`)
//line template.qtpl:479
			qw422016.E().S(cTempName(p))
//line template.qtpl:479
			qw422016.N().S(`)
`)
//line template.qtpl:480
		} else if isSlice, argLen := p.IsSliceParam(); isSlice {
//line template.qtpl:480
			qw422016.N().S(`	`)
//line template.qtpl:481
			qw422016.E().S(goParamName(p))
//line template.qtpl:481
			qw422016.N().S(` = make([]`)
//line template.qtpl:481
			qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:481
			qw422016.N().S(`, *`)
//line template.qtpl:481
			qw422016.E().S(argLen)
//line template.qtpl:481
			qw422016.N().S(`)
	_`)
//line template.qtpl:482
			qw422016.E().S(cTempName(p))
//line template.qtpl:482
			qw422016.N().S(` := (*[1 << 30](`)
//line template.qtpl:482
			qw422016.E().S(p.Type().Deref().GoCType())
//line template.qtpl:482
			qw422016.N().S(`))(unsafe.Pointer(`)
//line template.qtpl:482
			qw422016.E().S(cTempName(p))
//line template.qtpl:482
			qw422016.N().S(`))[:*`)
//line template.qtpl:482
			qw422016.E().S(argLen)
//line template.qtpl:482
			qw422016.N().S(`:*`)
//line template.qtpl:482
			qw422016.E().S(argLen)
//line template.qtpl:482
			qw422016.N().S(`]
	for i := C.size_t(0); i `)
//line template.qtpl:483
			qw422016.N().S("<")
//line template.qtpl:483
			qw422016.N().S(` *`)
//line template.qtpl:483
			qw422016.E().S(argLen)
//line template.qtpl:483
			qw422016.N().S(`; i++ {
		`)
//line template.qtpl:484
			qw422016.E().S(goParamName(p))
//line template.qtpl:484
			qw422016.N().S(`[i] = new`)
//line template.qtpl:484
			qw422016.E().S(p.Type().Deref().Deref().GoType())
//line template.qtpl:484
			qw422016.N().S(`(_`)
//line template.qtpl:484
			qw422016.E().S(cTempName(p))
//line template.qtpl:484
			qw422016.N().S(`[i])
	}
`)
//line template.qtpl:486
		} else if p.Type().Ty == parser.TyStringT {
//line template.qtpl:486
			qw422016.N().S(`	`)
//line template.qtpl:487
			qw422016.E().S(goParamName(p))
//line template.qtpl:487
			qw422016.N().S(` = string_from_cef_string(`)
//line template.qtpl:487
			qw422016.E().S(cTempName(p))
//line template.qtpl:487
			qw422016.N().S(`)
`)
//line template.qtpl:488
		} else if p.Type().Deref().IsRefCountedClass() {
//line template.qtpl:488
			qw422016.N().S(`	`)
//line template.qtpl:489
			qw422016.E().S(goParamName(p))
//line template.qtpl:489
			qw422016.N().S(` = new`)
//line template.qtpl:489
			qw422016.E().S(p.Type().Deref().Deref().GoType())
//line template.qtpl:489
			qw422016.N().S(`(`)
//line template.qtpl:489
			qw422016.E().S(cTempName(p))
//line template.qtpl:489
			qw422016.N().S(`)
`)
//line template.qtpl:490
		} else if p.Type().Ty == parser.TyTimeT {
//line template.qtpl:490
			qw422016.N().S(`
	`)
//line template.qtpl:491
			qw422016.E().S(goParamName(p))
//line template.qtpl:491
			qw422016.N().S(` = time.Unix(int64(`)
//line template.qtpl:491
			streamcTempName(qw422016, p)
//line template.qtpl:491
			qw422016.N().S(`), 0)
`)
//line template.qtpl:492
		} else {
//line template.qtpl:492
			qw422016.N().S(`	`)
//line template.qtpl:493
			qw422016.E().S(goParamName(p))
//line template.qtpl:493
			qw422016.N().S(` = (`)
//line template.qtpl:493
			qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:493
			qw422016.N().S(`)(`)
//line template.qtpl:493
			qw422016.E().S(cTempName(p))
//line template.qtpl:493
			qw422016.N().S(`)
`)
//line template.qtpl:494
		}
//line template.qtpl:495
	} else if ok, _ := p.IsByteSliceParam(); ok && !p.IsInOutParam() {
//line template.qtpl:495
		qw422016.N().S(`	C.free(`)
//line template.qtpl:496
		qw422016.E().S(cTempName(p))
//line template.qtpl:496
		qw422016.N().S(`)
`)
//line template.qtpl:497
	}
//line template.qtpl:498
}

//line template.qtpl:498
func writepostConvFromC(qq422016 qtio422016.Writer, p parser.Param, line *int) {
//line template.qtpl:498
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:498
	streampostConvFromC(qw422016, p, line)
//line template.qtpl:498
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:498
}

//line template.qtpl:498
func postConvFromC(p parser.Param, line *int) string {
//line template.qtpl:498
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:498
	writepostConvFromC(qb422016, p, line)
//line template.qtpl:498
	qs422016 := string(qb422016.B)
//line template.qtpl:498
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:498
	return qs422016
//line template.qtpl:498
}

//line template.qtpl:500
func StreamGoFunction(qw422016 *qt422016.Writer, line int, f *parser.FuncDecl) {
//line template.qtpl:500
	qw422016.N().S(`func `)
//line template.qtpl:501
	qw422016.E().S(f.Funcname.TitleCase())
//line template.qtpl:501
	qw422016.N().S(`(
`)
//line template.qtpl:502
	for _, p := range f.Params() {
//line template.qtpl:503
		if !p.IsByteSliceLengthParam() && !p.IsSliceLengthParam() && !p.IsOutParam() {
//line template.qtpl:503
			qw422016.N().S(`	`)
//line template.qtpl:504
			qw422016.E().S(goParamName(p))
//line template.qtpl:504
			qw422016.N().S(` `)
//line template.qtpl:504
			qw422016.E().S(p.GoType())
//line template.qtpl:504
			qw422016.N().S(`,
`)
//line template.qtpl:505
		}
//line template.qtpl:506
	}
//line template.qtpl:506
	qw422016.N().S(`) `)
//line template.qtpl:507
	streamretTypes(qw422016, f)
//line template.qtpl:507
	qw422016.N().S(`{
`)
//line template.qtpl:508
	for _, p := range f.Params() {
//line template.qtpl:509
		if exp := preConvToC(p, &line); exp != "" {
//line template.qtpl:510
			qw422016.N().S(exp)
//line template.qtpl:511
		}
//line template.qtpl:512
	}
//line template.qtpl:512
	qw422016.N().S(`
	`)
//line template.qtpl:513
	if f.HasReturnValue() {
//line template.qtpl:513
		qw422016.N().S(`cRet := `)
//line template.qtpl:513
	}
//line template.qtpl:513
	qw422016.N().S(`C.`)
//line template.qtpl:513
	qw422016.E().S(f.CefName())
//line template.qtpl:513
	qw422016.N().S(`(`)
//line template.qtpl:513
	for i, p := range f.Params() {
//line template.qtpl:514
		if i > 0 {
//line template.qtpl:514
			qw422016.N().S(`, `)
//line template.qtpl:514
		}
//line template.qtpl:514
		streamconvToC(qw422016, p)
//line template.qtpl:515
	}
//line template.qtpl:515
	qw422016.N().S(`)

`)
//line template.qtpl:517
	for _, p := range f.Params() {
//line template.qtpl:517
		streampostConvFromC(qw422016, p, &line)
//line template.qtpl:517
	}
//line template.qtpl:517
	qw422016.N().S(`	`)
//line template.qtpl:518
	streamgoReturnStmt(qw422016, f)
//line template.qtpl:518
	qw422016.N().S(`
}
`)
//line template.qtpl:520
}

//line template.qtpl:520
func WriteGoFunction(qq422016 qtio422016.Writer, line int, f *parser.FuncDecl) {
//line template.qtpl:520
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:520
	StreamGoFunction(qw422016, line, f)
//line template.qtpl:520
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:520
}

//line template.qtpl:520
func GoFunction(line int, f *parser.FuncDecl) string {
//line template.qtpl:520
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:520
	WriteGoFunction(qb422016, line, f)
//line template.qtpl:520
	qs422016 := string(qb422016.B)
//line template.qtpl:520
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:520
	return qs422016
//line template.qtpl:520
}

// Generate Go func Return Types

//line template.qtpl:523
func streamretTypes(qw422016 *qt422016.Writer, m parser.Callable) {
//line template.qtpl:524
	if m.HasReturnValue() || m.HasOutParam() {
//line template.qtpl:524
		qw422016.N().S(`(`)
//line template.qtpl:525
		if m.HasReturnValue() {
//line template.qtpl:525
			qw422016.N().S(`ret `)
//line template.qtpl:525
			qw422016.E().S(m.ReturnGoType())
//line template.qtpl:525
			qw422016.N().S(`,`)
//line template.qtpl:525
		}
//line template.qtpl:526
		for _, p := range m.Params() {
//line template.qtpl:527
			if p.IsOutParam() || p.IsInOutParam() {
//line template.qtpl:528
				qw422016.E().S(goParamNameOut(p) + " ")
//line template.qtpl:529
				if p.Type().Ty == parser.TyStringT && p.Type().Pointer == 1 {
//line template.qtpl:530
					qw422016.E().S(p.Type().GoType())
//line template.qtpl:531
				} else if isSlice, _ := p.IsSliceParam(); isSlice {
//line template.qtpl:532
					qw422016.E().S("[]" + p.Type().Deref().GoType())
//line template.qtpl:533
				} else if isSlice, _ := p.IsByteSliceParam(); isSlice {
//line template.qtpl:534
					qw422016.E().S("[]byte")
//line template.qtpl:535
				} else if p.IsBoolParam() {
//line template.qtpl:536
					qw422016.E().S("bool")
//line template.qtpl:537
				} else {
//line template.qtpl:538
					qw422016.E().S(p.Type().Deref().GoType())
//line template.qtpl:539
				}
//line template.qtpl:539
				qw422016.N().S(`, `)
//line template.qtpl:540
			}
//line template.qtpl:541
		}
//line template.qtpl:542
		qw422016.E().S(")")
//line template.qtpl:543
	}
//line template.qtpl:544
}

//line template.qtpl:544
func writeretTypes(qq422016 qtio422016.Writer, m parser.Callable) {
//line template.qtpl:544
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:544
	streamretTypes(qw422016, m)
//line template.qtpl:544
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:544
}

//line template.qtpl:544
func retTypes(m parser.Callable) string {
//line template.qtpl:544
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:544
	writeretTypes(qb422016, m)
//line template.qtpl:544
	qs422016 := string(qb422016.B)
//line template.qtpl:544
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:544
	return qs422016
//line template.qtpl:544
}

// Generate Go method call to object method (self->method(...))

//line template.qtpl:547
func StreamCefObjectMethod(qw422016 *qt422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:547
	qw422016.N().S(`
`)
//line template.qtpl:548
	for _, c := range m.Comment {
//line template.qtpl:549
		qw422016.E().S(c)
//line template.qtpl:549
		qw422016.N().S(`
`)
//line template.qtpl:550
	}
//line template.qtpl:550
	qw422016.N().S(`func  (`)
//line template.qtpl:551
	qw422016.E().S(goParamName(m.Params()[0]))
//line template.qtpl:551
	qw422016.N().S(` `)
//line template.qtpl:551
	qw422016.E().S(m.Params()[0].GoType())
//line template.qtpl:551
	qw422016.N().S(`) `)
//line template.qtpl:551
	qw422016.E().S(m.Funcname.TitleCase())
//line template.qtpl:551
	qw422016.N().S(`(
`)
//line template.qtpl:552
	for i, p := range m.Params() {
//line template.qtpl:553
		if i > 0 && !p.IsOutParam() {
//line template.qtpl:554
			if !p.IsByteSliceLengthParam() && !p.IsSliceLengthParam() {
//line template.qtpl:554
				qw422016.N().S(`	`)
//line template.qtpl:555
				qw422016.E().S(goParamName(p))
//line template.qtpl:555
				qw422016.N().S(` `)
//line template.qtpl:555
				qw422016.E().S(p.GoType())
//line template.qtpl:555
				qw422016.N().S(`,
`)
//line template.qtpl:556
			}
//line template.qtpl:557
		}
//line template.qtpl:558
	}
//line template.qtpl:558
	qw422016.N().S(`) `)
//line template.qtpl:559
	streamretTypes(qw422016, m)
//line template.qtpl:559
	qw422016.N().S(`{
`)
//line template.qtpl:560
	for i, p := range m.Params() {
//line template.qtpl:561
		if !(i == 0 && p.Name() == "self") {
//line template.qtpl:562
			if stmts := preConvToC(p, &line); stmts != "" {
//line template.qtpl:563
				qw422016.N().S(stmts)
//line template.qtpl:564
			}
//line template.qtpl:565
		}
//line template.qtpl:566
	}
//line template.qtpl:566
	qw422016.N().S(`
	`)
//line template.qtpl:567
	if m.HasReturnValue() {
//line template.qtpl:567
		qw422016.N().S(`cRet := `)
//line template.qtpl:567
	}
//line template.qtpl:567
	qw422016.N().S(`C.`)
//line template.qtpl:567
	qw422016.E().S(methodCName(m))
//line template.qtpl:567
	qw422016.N().S(`(`)
//line template.qtpl:567
	for i, p := range m.Params() {
//line template.qtpl:568
		if i > 0 {
//line template.qtpl:568
			qw422016.N().S(`, `)
//line template.qtpl:568
		}
//line template.qtpl:568
		streamconvToC(qw422016, p)
//line template.qtpl:569
	}
//line template.qtpl:569
	qw422016.N().S(`)

`)
//line template.qtpl:571
	for _, p := range m.Params() {
//line template.qtpl:571
		streampostConvFromC(qw422016, p, &line)
//line template.qtpl:571
	}
//line template.qtpl:572
	streamgoReturnStmt(qw422016, m)
//line template.qtpl:572
	qw422016.N().S(`
}
`)
//line template.qtpl:574
}

//line template.qtpl:574
func WriteCefObjectMethod(qq422016 qtio422016.Writer, line int, m *parser.MethodDecl) {
//line template.qtpl:574
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:574
	StreamCefObjectMethod(qw422016, line, m)
//line template.qtpl:574
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:574
}

//line template.qtpl:574
func CefObjectMethod(line int, m *parser.MethodDecl) string {
//line template.qtpl:574
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:574
	WriteCefObjectMethod(qb422016, line, m)
//line template.qtpl:574
	qs422016 := string(qb422016.B)
//line template.qtpl:574
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:574
	return qs422016
//line template.qtpl:574
}

//line template.qtpl:576
func streamgoReturnStmt(qw422016 *qt422016.Writer, m parser.Callable) {
//line template.qtpl:577
	if m.HasReturnValue() {
//line template.qtpl:578
		if m.IsBoolValueMethod() {
//line template.qtpl:578
			qw422016.N().S(`
	ret = cRet == 1
`)
//line template.qtpl:580
		} else if m.ReturnType().Ty == parser.TyStringUserfreeT {
//line template.qtpl:580
			qw422016.N().S(`
	s := string_from_cef_string((*C.cef_string_t)(cRet))
	if cRet != nil {
		C.cef_string_userfree_free(cRet)
	}
	ret = s
`)
//line template.qtpl:586
		} else {
//line template.qtpl:586
			qw422016.N().S(`
	ret = `)
//line template.qtpl:587
			qw422016.E().S(ConvToGoTypeExp(m.ReturnType(), "cRet"))
//line template.qtpl:587
			qw422016.N().S(`
`)
//line template.qtpl:588
		}
//line template.qtpl:589
	}
//line template.qtpl:590
	if m.HasReturnValue() || m.HasOutParam() {
//line template.qtpl:590
		first := true

//line template.qtpl:590
		qw422016.N().S(`	return `)
//line template.qtpl:591
		if m.HasReturnValue() {
//line template.qtpl:591
			qw422016.N().S(`ret`)
//line template.qtpl:591
			first = false

//line template.qtpl:591
		}
//line template.qtpl:592
		for _, p := range m.Params() {
//line template.qtpl:593
			if p.IsOutParam() || p.IsInOutParam() {
//line template.qtpl:594
				if !first {
//line template.qtpl:594
					qw422016.N().S(`, `)
//line template.qtpl:594
				}
//line template.qtpl:594
				qw422016.E().S(goParamName(p))
//line template.qtpl:594
				first = false

//line template.qtpl:595
			}
//line template.qtpl:596
		}
//line template.qtpl:597
	}
//line template.qtpl:598
}

//line template.qtpl:598
func writegoReturnStmt(qq422016 qtio422016.Writer, m parser.Callable) {
//line template.qtpl:598
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:598
	streamgoReturnStmt(qw422016, m)
//line template.qtpl:598
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:598
}

//line template.qtpl:598
func goReturnStmt(m parser.Callable) string {
//line template.qtpl:598
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:598
	writegoReturnStmt(qb422016, m)
//line template.qtpl:598
	qs422016 := string(qb422016.B)
//line template.qtpl:598
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:598
	return qs422016
//line template.qtpl:598
}

//line template.qtpl:600
func streammethodCName(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:601
	qw422016.E().S("cefingo_" + m.ClassBaseName() + "_" + m.Funcname.Name())
//line template.qtpl:602
}

//line template.qtpl:602
func writemethodCName(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:602
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:602
	streammethodCName(qw422016, m)
//line template.qtpl:602
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:602
}

//line template.qtpl:602
func methodCName(m *parser.MethodDecl) string {
//line template.qtpl:602
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:602
	writemethodCName(qb422016, m)
//line template.qtpl:602
	qs422016 := string(qb422016.B)
//line template.qtpl:602
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:602
	return qs422016
//line template.qtpl:602
}

//line template.qtpl:604
func streammethodCSig(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:605
	qw422016.E().S(m.ReturnType().CType())
//line template.qtpl:605
	qw422016.N().S(` `)
//line template.qtpl:605
	qw422016.E().S(methodCName(m))
//line template.qtpl:605
	qw422016.N().S(`(
`)
//line template.qtpl:606
	for i, p := range m.Params() {
//line template.qtpl:607
		if i > 0 {
//line template.qtpl:607
			qw422016.N().S(`,
`)
//line template.qtpl:608
		}
//line template.qtpl:608
		qw422016.N().S(`	`)
//line template.qtpl:609
		qw422016.E().S(p.CType())
//line template.qtpl:609
		qw422016.N().S(` `)
//line template.qtpl:609
		qw422016.E().S(p.Name())
//line template.qtpl:610
	}
//line template.qtpl:610
	qw422016.N().S(`
`)
//line template.qtpl:611
	qw422016.E().S(")")
//line template.qtpl:612
}

//line template.qtpl:612
func writemethodCSig(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:612
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:612
	streammethodCSig(qw422016, m)
//line template.qtpl:612
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:612
}

//line template.qtpl:612
func methodCSig(m *parser.MethodDecl) string {
//line template.qtpl:612
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:612
	writemethodCSig(qb422016, m)
//line template.qtpl:612
	qs422016 := string(qb422016.B)
//line template.qtpl:612
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:612
	return qs422016
//line template.qtpl:612
}

//line template.qtpl:614
func StreamCefObjectMethodH(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:614
	qw422016.N().S(`
extern `)
//line template.qtpl:615
	qw422016.E().S(methodCSig(m))
//line template.qtpl:615
	qw422016.N().S(`;
`)
//line template.qtpl:616
}

//line template.qtpl:616
func WriteCefObjectMethodH(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:616
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:616
	StreamCefObjectMethodH(qw422016, m)
//line template.qtpl:616
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:616
}

//line template.qtpl:616
func CefObjectMethodH(m *parser.MethodDecl) string {
//line template.qtpl:616
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:616
	WriteCefObjectMethodH(qb422016, m)
//line template.qtpl:616
	qs422016 := string(qb422016.B)
//line template.qtpl:616
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:616
	return qs422016
//line template.qtpl:616
}

//line template.qtpl:618
func StreamCefObjectMethodC(qw422016 *qt422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:618
	qw422016.N().S(`
`)
//line template.qtpl:619
	retGoType := m.ReturnGoType()

//line template.qtpl:620
	qw422016.E().S(methodCSig(m))
//line template.qtpl:620
	qw422016.N().S(`
{
	`)
//line template.qtpl:622
	if retGoType != "" {
//line template.qtpl:622
		qw422016.N().S(`return `)
//line template.qtpl:622
	}
//line template.qtpl:622
	qw422016.N().S(`self->`)
//line template.qtpl:622
	qw422016.E().S(m.Funcname.Name())
//line template.qtpl:622
	qw422016.N().S(`(
`)
//line template.qtpl:623
	for i, p := range m.Params() {
//line template.qtpl:624
		if i > 0 {
//line template.qtpl:624
			qw422016.N().S(`, 
`)
//line template.qtpl:625
		}
//line template.qtpl:625
		qw422016.N().S(`		`)
//line template.qtpl:626
		qw422016.E().S(p.Name())
//line template.qtpl:627
	}
//line template.qtpl:627
	qw422016.N().S(`
	);
}
`)
//line template.qtpl:630
}

//line template.qtpl:630
func WriteCefObjectMethodC(qq422016 qtio422016.Writer, m *parser.MethodDecl) {
//line template.qtpl:630
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:630
	StreamCefObjectMethodC(qw422016, m)
//line template.qtpl:630
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:630
}

//line template.qtpl:630
func CefObjectMethodC(m *parser.MethodDecl) string {
//line template.qtpl:630
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:630
	WriteCefObjectMethodC(qb422016, m)
//line template.qtpl:630
	qs422016 := string(qb422016.B)
//line template.qtpl:630
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:630
	return qs422016
//line template.qtpl:630
}

// newCXxxxT()

//line template.qtpl:633
func StreamGoType(qw422016 *qt422016.Writer, d *parser.CefClassDecl, line int) {
//line template.qtpl:633
	qw422016.N().S(`
`)
//line template.qtpl:634
	goName := d.Token().GoName()
	cName := d.Token().Name()
	typeName := d.Token().BaseName()
	line = line + 25

//line template.qtpl:638
	qw422016.N().S(`// Go type for `)
//line template.qtpl:639
	qw422016.E().S(cName)
//line template.qtpl:639
	qw422016.N().S(`	
type `)
//line template.qtpl:640
	qw422016.E().S(goName)
//line template.qtpl:640
	qw422016.N().S(` struct {
	noCopy noCopy
	p_`)
//line template.qtpl:642
	qw422016.E().S(typeName)
//line template.qtpl:642
	qw422016.N().S(` *C.`)
//line template.qtpl:642
	qw422016.E().S(cName)
//line template.qtpl:642
	qw422016.N().S(`
}

type RefTo`)
//line template.qtpl:645
	qw422016.E().S(goName)
//line template.qtpl:645
	qw422016.N().S(` struct {
	p_`)
//line template.qtpl:646
	qw422016.E().S(typeName)
//line template.qtpl:646
	qw422016.N().S(` *`)
//line template.qtpl:646
	qw422016.E().S(goName)
//line template.qtpl:646
	qw422016.N().S(`
}

type `)
//line template.qtpl:649
	qw422016.E().S(goName)
//line template.qtpl:649
	qw422016.N().S(`Accessor interface {
	Get`)
//line template.qtpl:650
	qw422016.E().S(goName)
//line template.qtpl:650
	qw422016.N().S(`() *`)
//line template.qtpl:650
	qw422016.E().S(goName)
//line template.qtpl:650
	qw422016.N().S(`
	Set`)
//line template.qtpl:651
	qw422016.E().S(goName)
//line template.qtpl:651
	qw422016.N().S(`(*`)
//line template.qtpl:651
	qw422016.E().S(goName)
//line template.qtpl:651
	qw422016.N().S(`)
}

func (r RefTo`)
//line template.qtpl:654
	qw422016.E().S(goName)
//line template.qtpl:654
	qw422016.N().S(`) Get`)
//line template.qtpl:654
	qw422016.E().S(goName)
//line template.qtpl:654
	qw422016.N().S(`() *`)
//line template.qtpl:654
	qw422016.E().S(goName)
//line template.qtpl:654
	qw422016.N().S(` {
	return r.p_`)
//line template.qtpl:655
	qw422016.E().S(typeName)
//line template.qtpl:655
	qw422016.N().S(`
}

func (r *RefTo`)
//line template.qtpl:658
	qw422016.E().S(goName)
//line template.qtpl:658
	qw422016.N().S(`) Set`)
//line template.qtpl:658
	qw422016.E().S(goName)
//line template.qtpl:658
	qw422016.N().S(`(p *`)
//line template.qtpl:658
	qw422016.E().S(goName)
//line template.qtpl:658
	qw422016.N().S(`) {
	r.p_`)
//line template.qtpl:659
	qw422016.E().S(typeName)
//line template.qtpl:659
	qw422016.N().S(` = p
}

// Go type `)
//line template.qtpl:662
	qw422016.E().S(goName)
//line template.qtpl:662
	qw422016.N().S(` wraps cef type *C.`)
//line template.qtpl:662
	qw422016.E().S(cName)
//line template.qtpl:662
	qw422016.N().S(`
func new`)
//line template.qtpl:663
	qw422016.E().S(goName)
//line template.qtpl:663
	qw422016.N().S(`(p *C.`)
//line template.qtpl:663
	qw422016.E().S(cName)
//line template.qtpl:663
	qw422016.N().S(`) *`)
//line template.qtpl:663
	qw422016.E().S(goName)
//line template.qtpl:663
	qw422016.N().S(` {
	if p == nil {
		return nil
	}
	Tracef(unsafe.Pointer(p), "T`)
//line template.qtpl:667
	qw422016.N().D(line + 4)
//line template.qtpl:667
	qw422016.N().S(`:")
`)
//line template.qtpl:668
	if d.St == parser.StRefCounted {
//line template.qtpl:668
		qw422016.N().S(`	BaseAddRef(p)
`)
//line template.qtpl:670
	}
//line template.qtpl:670
	qw422016.N().S(`	go_`)
//line template.qtpl:671
	qw422016.E().S(typeName)
//line template.qtpl:671
	qw422016.N().S(` := `)
//line template.qtpl:671
	qw422016.E().S(goName)
//line template.qtpl:671
	qw422016.N().S(`{noCopy{}, p}
`)
//line template.qtpl:672
	if d.St == parser.StRefCounted {
//line template.qtpl:672
		qw422016.N().S(`	runtime.SetFinalizer(&go_`)
//line template.qtpl:673
		qw422016.E().S(typeName)
//line template.qtpl:673
		qw422016.N().S(`, func(g *`)
//line template.qtpl:673
		qw422016.E().S(goName)
//line template.qtpl:673
		qw422016.N().S(`) {
		Tracef(unsafe.Pointer(g.p_`)
//line template.qtpl:674
		qw422016.E().S(typeName)
//line template.qtpl:674
		qw422016.N().S(`), "T`)
//line template.qtpl:674
		qw422016.N().D(line + 8)
//line template.qtpl:674
		qw422016.N().S(`:")
		BaseRelease(g.p_`)
//line template.qtpl:675
		qw422016.E().S(typeName)
//line template.qtpl:675
		qw422016.N().S(`)
	})
`)
//line template.qtpl:677
	}
//line template.qtpl:677
	qw422016.N().S(`	return &go_`)
//line template.qtpl:678
	qw422016.E().S(typeName)
//line template.qtpl:678
	qw422016.N().S(`
}
`)
//line template.qtpl:680
	if d.St == parser.StRefCounted {
//line template.qtpl:680
		qw422016.N().S(`// *C.`)
//line template.qtpl:681
		qw422016.E().S(cName)
//line template.qtpl:681
		qw422016.N().S(` has refCounted interface
func (`)
//line template.qtpl:682
		qw422016.E().S(typeName)
//line template.qtpl:682
		qw422016.N().S(` *`)
//line template.qtpl:682
		qw422016.E().S(goName)
//line template.qtpl:682
		qw422016.N().S(`) HasOneRef() bool {
	return BaseHasOneRef(`)
//line template.qtpl:683
		qw422016.E().S(typeName)
//line template.qtpl:683
		qw422016.N().S(`.p_`)
//line template.qtpl:683
		qw422016.E().S(typeName)
//line template.qtpl:683
		qw422016.N().S(`)
}

func (p *C.`)
//line template.qtpl:686
		qw422016.E().S(cName)
//line template.qtpl:686
		qw422016.N().S(`) cast_to_p_base_ref_counted_t() *C.cef_base_ref_counted_t {
	return (*C.cef_base_ref_counted_t)(unsafe.Pointer(p))
}
`)
//line template.qtpl:689
	}
//line template.qtpl:690
}

//line template.qtpl:690
func WriteGoType(qq422016 qtio422016.Writer, d *parser.CefClassDecl, line int) {
//line template.qtpl:690
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:690
	StreamGoType(qw422016, d, line)
//line template.qtpl:690
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:690
}

//line template.qtpl:690
func GoType(d *parser.CefClassDecl, line int) string {
//line template.qtpl:690
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:690
	WriteGoType(qb422016, d, line)
//line template.qtpl:690
	qs422016 := string(qb422016.B)
//line template.qtpl:690
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:690
	return qs422016
//line template.qtpl:690
}

//line template.qtpl:692
func streamcField(qw422016 *qt422016.Writer, f string) {
//line template.qtpl:693
	if f == "type" || f == "range" {
//line template.qtpl:693
		qw422016.N().S(`_`)
//line template.qtpl:693
		qw422016.E().S(f)
//line template.qtpl:693
	} else {
//line template.qtpl:693
		qw422016.E().S(f)
//line template.qtpl:693
	}
//line template.qtpl:694
}

//line template.qtpl:694
func writecField(qq422016 qtio422016.Writer, f string) {
//line template.qtpl:694
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:694
	streamcField(qw422016, f)
//line template.qtpl:694
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:694
}

//line template.qtpl:694
func cField(f string) string {
//line template.qtpl:694
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:694
	writecField(qb422016, f)
//line template.qtpl:694
	qs422016 := string(qb422016.B)
//line template.qtpl:694
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:694
	return qs422016
//line template.qtpl:694
}

//line template.qtpl:696
func streamcastGoType(qw422016 *qt422016.Writer, s string) {
//line template.qtpl:697
	if s == "C.VOIDP" {
//line template.qtpl:697
		qw422016.N().S(`unsafe.Pointer`)
//line template.qtpl:697
	} else {
//line template.qtpl:697
		qw422016.E().S(s)
//line template.qtpl:697
	}
//line template.qtpl:697
}

//line template.qtpl:697
func writecastGoType(qq422016 qtio422016.Writer, s string) {
//line template.qtpl:697
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:697
	streamcastGoType(qw422016, s)
//line template.qtpl:697
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:697
}

//line template.qtpl:697
func castGoType(s string) string {
//line template.qtpl:697
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:697
	writecastGoType(qb422016, s)
//line template.qtpl:697
	qs422016 := string(qb422016.B)
//line template.qtpl:697
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:697
	return qs422016
//line template.qtpl:697
}

//line template.qtpl:699
func StreamMemberAccessor(qw422016 *qt422016.Writer, d *parser.StructDecl, m parser.Member) {
//line template.qtpl:699
	qw422016.N().S(`func (st *`)
//line template.qtpl:700
	qw422016.E().S(d.GoName())
//line template.qtpl:700
	qw422016.N().S(`) `)
//line template.qtpl:700
	qw422016.E().S(m.GoName())
//line template.qtpl:700
	qw422016.N().S(`() `)
//line template.qtpl:700
	qw422016.E().S(m.GoType())
//line template.qtpl:700
	qw422016.N().S(` {
`)
//line template.qtpl:701
	if m.Type().Ty == parser.TyStringT && m.Type().Pointer == 0 {
//line template.qtpl:701
		qw422016.N().S(`	return string_from_cef_string(&st.`)
//line template.qtpl:702
		qw422016.E().S(cField(m.Name()))
//line template.qtpl:702
		qw422016.N().S(`)
`)
//line template.qtpl:703
	} else {
//line template.qtpl:703
		qw422016.N().S(`	return `)
//line template.qtpl:704
		qw422016.E().S(m.GoType())
//line template.qtpl:704
		qw422016.N().S(`(st.`)
//line template.qtpl:704
		qw422016.E().S(cField(m.Name()))
//line template.qtpl:704
		qw422016.N().S(`)
`)
//line template.qtpl:705
	}
//line template.qtpl:705
	qw422016.N().S(`}

func (st *`)
//line template.qtpl:708
	qw422016.E().S(d.GoName())
//line template.qtpl:708
	qw422016.N().S(`) Set`)
//line template.qtpl:708
	qw422016.E().S(m.GoName())
//line template.qtpl:708
	qw422016.N().S(`(v `)
//line template.qtpl:708
	qw422016.E().S(m.GoType())
//line template.qtpl:708
	qw422016.N().S(`) {
`)
//line template.qtpl:709
	if m.Type().Ty == parser.TyStringT && m.Type().Pointer == 0 {
//line template.qtpl:709
		qw422016.N().S(`	set_cef_string(&st.`)
//line template.qtpl:710
		qw422016.E().S(cField(m.Name()))
//line template.qtpl:710
		qw422016.N().S(`, v)
`)
//line template.qtpl:711
	} else {
//line template.qtpl:711
		qw422016.N().S(`	st.`)
//line template.qtpl:712
		qw422016.E().S(cField(m.Name()))
//line template.qtpl:712
		qw422016.N().S(` = (`)
//line template.qtpl:712
		qw422016.E().S(castGoType(m.Type().GoCType()))
//line template.qtpl:712
		qw422016.N().S(`)(v)
`)
//line template.qtpl:713
	}
//line template.qtpl:713
	qw422016.N().S(`}

`)
//line template.qtpl:716
}

//line template.qtpl:716
func WriteMemberAccessor(qq422016 qtio422016.Writer, d *parser.StructDecl, m parser.Member) {
//line template.qtpl:716
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:716
	StreamMemberAccessor(qw422016, d, m)
//line template.qtpl:716
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:716
}

//line template.qtpl:716
func MemberAccessor(d *parser.StructDecl, m parser.Member) string {
//line template.qtpl:716
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:716
	WriteMemberAccessor(qb422016, d, m)
//line template.qtpl:716
	qs422016 := string(qb422016.B)
//line template.qtpl:716
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:716
	return qs422016
//line template.qtpl:716
}

//line template.qtpl:718
func StreamNewStruct(qw422016 *qt422016.Writer, d *parser.StructDecl) {
//line template.qtpl:718
	qw422016.N().S(`func New`)
//line template.qtpl:719
	qw422016.E().S(d.GoName())
//line template.qtpl:719
	qw422016.N().S(`() *`)
//line template.qtpl:719
	qw422016.E().S(d.GoName())
//line template.qtpl:719
	qw422016.N().S(` {
	s := &`)
//line template.qtpl:720
	qw422016.E().S(d.GoName())
//line template.qtpl:720
	qw422016.N().S(`{}
`)
//line template.qtpl:721
	if d.Members[0].Type().Ty == parser.TySizeT && d.Members[0].Name() == "size" {
//line template.qtpl:721
		qw422016.N().S(`	s.size = C.sizeof_`)
//line template.qtpl:722
		qw422016.E().S(d.CefName())
//line template.qtpl:722
		qw422016.N().S(`
`)
//line template.qtpl:723
	}
//line template.qtpl:723
	qw422016.N().S(`	return s
}

`)
//line template.qtpl:727
}

//line template.qtpl:727
func WriteNewStruct(qq422016 qtio422016.Writer, d *parser.StructDecl) {
//line template.qtpl:727
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:727
	StreamNewStruct(qw422016, d)
//line template.qtpl:727
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:727
}

//line template.qtpl:727
func NewStruct(d *parser.StructDecl) string {
//line template.qtpl:727
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:727
	WriteNewStruct(qb422016, d)
//line template.qtpl:727
	qs422016 := string(qb422016.B)
//line template.qtpl:727
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:727
	return qs422016
//line template.qtpl:727
}
